### ISSUE TITLE
Stratos | World Generator support request

### ISSUE THREAD

**Issue by 6roke** [PluginBugs/Issues-ItemsAdder#1026]
Hey, I hope you can add this world generator compatibility in the future.

(I am trying to preload chunks with Chunky using Stratos Generator ofc and I am getting this error)

Log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/6795427/latest.log)

**Comment by LoneDev6** [comment]
I contacted the author, only them can add compatibility with itemsadder, I can't do much about that

**Comment by LoneDev6** [comment]
You have to contact Stratos devs in order to tell them to add compatibility to ItemsAdder.
If needed I can provide a free copy of ItemsAdder to the developers.

(ItemsAdder has a free easy to use API, but if they want to test the functionality they have to own the plugin)
https://itemsadder.devs.beer/developers/java-api/examples
