### ISSUE TITLE
[BUG] RESOURCE PACK IS BUGGY

### ISSUE THREAD

**Issue by xonfirex1** [PluginBugs/Issues-ItemsAdder#1042]
**Describe the bug**
The resource pack is badly designed, I deleted the itemsadder folder so that it would install cleanly, but when I put the command /ia it is all messed up, with the textures changed, e.g. the textures of the icons are in the one of the blocks.

**To Reproduce**
1. open the itemsadder menu  '/ia'
2. See the all items with the resourcepack bug, the icons are in the blocks

**Expected behavior**
I just think the resource pack is badly distributed, the plugin is excellent, but I need to fix that problem. 

**Screenshots**
https://prnt.sc/1b5k524

**Info (please complete the following information):**
 - Server version: paper 1.17.1
 - Client version: vanilla 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.3
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
It's normal.
You have to follow the installation tutorial in order to generate your own pack.
Each server needs to have its own pack because the default pack provided by ItemsAdder may not work on every server.

Following the installation tutorial will make it work fine.
There is even a video step by step:
https://itemsadder.devs.beer/first-install
