### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MusicTW** [PluginBugs/Issues-ItemsAdder#1054]
**Describe the bug**
It happened when i want to add my custom things inside the server

**To Reproduce**

**Expected behavior**
type /iareload or /iazip and show error
https://pastebin.com/aYQ3yKNd

**Screenshots**

**Info (please complete the following information):**
 - Server version: paper782 1.16.5
 - Client version: optifine 1.16.5

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.5
 - LightAPI Fork version: 3.5.1
  - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.1-SNAPSHOT-b530

**Additional context**

**Comment by LoneDev6** [comment]
as noted in the log:
> THIS IS NOT A BUG OR A CRASH

it just tells you the server is loading a lot of stuff and is stuck for some seconds due to this.
You can safely ignore that, it's normal. ItemsAdder is loading more than 500 items which is not an easy/lightweight task.

Don't worry it will happen only on server load or when you reload the plugin.
Consider adding more cores to your server if needed. For example with a i9 or Ryzen CPU I didn't ever had problems of this type.

Have a nice day
