### ISSUE TITLE
after i added a new Model i got a Error and sun and moon Stuttering | and performance problem

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1062]
**Describe the bug**
the sun and moon Stuttering after I add a model and restart the server I got a big error on Console and the problem still 
![sun](https://user-images.githubusercontent.com/68678154/126762888-8b91ff99-05de-40f9-92a3-93f9b8536d91.gif)

**To Reproduce**
1. I added a new model to my server it didn't need to show up and I restart the server and that's happened on the console after restart  ''
See error | https://paste.gg/p/anonymous/306c42f51739423b9f6347f39e171149

and this Error before I restart the server | https://paste.gg/p/anonymous/f3a83ee722ab47598d0b28e3bdaf702f

**Expected behavior**

**Info (please complete the following information):**
 - Server version: (git-Paper-782 (MC: 1.16.5))
 - Client version: (vanilla 1.16.5)

**Special Info**
 - ItemsAdder version: ItemsAdder v2.4.5
 - LightAPI Fork version: LightAPI v3.5.2
 - LoneLibs version: LoneLibs 1.0.14
 - ProtocolLib version:v4.7.0

**Comment by LoneDev6** [comment]
I don't see how the server time can be affected by itemsadder, I don't alter server time in any way so sun and moon can't lag because of itemsadder.

about the error, update LibsDisguises and ProtocolLib.


about this error
> Error saving model file modifications for new-weaponsclaymore
  | [10:33:22] [Server thread/WARN]: java.nio.file.AccessDeniedException: /home/container/plugins/ItemsAdder/data/resource_pack/assets/new-weapons/models


seems somehow files permissions don't allow itemadder to write this file, I have no idea what can cause this, it may be a problem of your FTP files permissions or caused by the hosting itself.
A note: the `new-weapons` folder must be names `new_weapons`. Minecraft doesn't allow some characters like `-` for example, this may be the cause of the problem.



anyway if the plugin worked fine until yesterday: something must be changed, try to remember what you changed.
itemsadder doesn't break on its own.

let me know how it goes, have a nice day
