### ISSUE TITLE
[BUG] REDACTED

### ISSUE THREAD

**Issue by Zoelleradada** [PluginBugs/Issues-ItemsAdder#1065]
**Describe the bug**
REDACTED

**Info (please complete the following information):**
 - Server version: 1.16.5
 - Client version:  1.16.5

**Special Info**
 - ItemsAdder version: 2.4.5
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
It's impossible to make this system uncrackable.
The method you described is similar on how Minecraft can read the resourcepack.
If I make the resourcepack completely unreadable how can Minecraft read it to show the textures/models?


There is sadly no way to make the resourcepack 100% protected because of how Mojang decided to implement this system and there is nothing else I can do to make it better.
Keep in mind that the current ItemsAdder method will make it difficult for kids and server admins to steal your pack.
Obviously most expert "hackers" will be able to tamper the protection, nothing is 100% protected in computer security.

Have a nice day

**Comment by LoneDev6** [comment]
In the future avoid opening a public report about this kind of stuff if you care about security. It's not a good idea to make this information public.

Please answer here once you've read the message so that I can delete the issue report as I don't know your Discord/Spigot username to contact you.
