### ISSUE TITLE
[Suggestion] Custom crop model

### ISSUE THREAD

**Issue by yebanme** [PluginBugs/Issues-ItemsAdder#1081]
**Is your feature request related to a problem? Please describe.**
Add support for custom crop models, another similar plugin has implemented similar functions,this will make the crop more interesting
[Oraxen ](https://www.spigotmc.org/resources/%E2%98%84%EF%B8%8F-oraxen-%C2%BB-custom-items-blocks-emojis-guis-and-more.72448/update?update=416471)
**Additional context**
![8d3ad8bead731ec4cec94690389c422e13b583cb](https://user-images.githubusercontent.com/20102749/127808842-8908558a-5d02-4c59-8697-95491504175b.png)

**Comment by LoneDev6** [comment]
Sadly I wish I've never get this news.
Oraxen is creating their custom crops using real server entities... prepare for a huge TPS and FPS drop.

In the future ItemsAdder will also provide custom crops features, but I'd prefer not to follow the "easy path" Oraxen devs decided to take because it will destroy your server.

**Comment by LoneDev6** [comment]
This discussion was continued on Discord and we all decided not to follow Oraxen path since it's a very bad way to create custom crops.
It has a lot of downsides, one of them is the FPS/TPS decrease which is awful.

Maybe in the future we will have another way.
More info here:
https://discord.com/channels/533407895010803753/871348543317770241/872527680225017896
