### ISSUE TITLE
Ketchup and Donut base dupe [BUG] 

### ISSUE THREAD

**Issue by Agaloth** [PluginBugs/Issues-ItemsAdder#1104]
**Describe the bug**
Placing sticks in inventory crafting table or simple in a crafting table will allow you to make ketchup or donut base then you can dupe the ketchup by placing a ketchup in the inventory and also make potato sticks with the donut base.

**To Reproduce**
1. Gather sticks
2. Place it in the inventory like this
![image](https://user-images.githubusercontent.com/33335971/129478986-0509c24a-b5cc-4e6f-8fd5-c08ef99b4e92.png)
![image](https://user-images.githubusercontent.com/33335971/129478990-68b820c5-1517-4954-867f-8e633ecf2d13.png)
![image](https://user-images.githubusercontent.com/33335971/129478994-85f7b7ac-7b3e-4352-b5a3-48348076c5c8.png)
![image](https://user-images.githubusercontent.com/33335971/129479000-ad031a27-3e43-4bc4-9d7f-2d6fbee3b346.png)
![image](https://user-images.githubusercontent.com/33335971/129479003-118be531-7ef5-42c5-8df3-fe897f62057d.png)
![image](https://user-images.githubusercontent.com/33335971/129479010-ee11c793-8648-405e-be04-5444f6ded71a.png)

**Expected behavior**
Craft nothing.

**Screenshots**
Sent on top to explain the craft.

**Info (please complete the following information):**
 - Server version: Airplane 1.16.5
 - Client version: Optifine/Vanilla 1.16.5

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: ItemsAdder version 2.4.8
 - LoneLibs version: LoneLibs version 1.0.14
 - ProtocolLib version: ProtocolLib version 4.6.1-SNAPSHOT-b501
 - CustomCrafting version 1.6.5.1.4

**Additional context**
It outputs an error with customcrafting, https://ghostbin.com/paste/HUO4w

Look at https://github.com/PluginBugs/Issues-ItemsAdder/issues/1094 on why I can't update the plugin.

**Comment by LoneDev6** [comment]
I'm sorry I can't allow multi version support for CustomCrafting.
You have to ask the CustomCrafting developer to allow Java 8 on the most recent version. I don't see why they decided to cut off Java 8 support since a lot of servers still rely on this version.

I hope you understand I don't have much control over other plugins authors and CustomCrafting developers is known to change their API a lot on each update, so I do my best to make IA compatible with most recent versions. I can't code a compatibility logic for each version of each plugin.

Thanks for the patience.
