### ISSUE TITLE
[Suggestion] Space Plugin Support

### ISSUE THREAD

**Issue by dabai233** [PluginBugs/Issues-ItemsAdder#1108]
**Is your feature request related to a problem? Please describe.**
https://www.spigotmc.org/resources/space.59572/
please support the Space plugin
I tried to merge the resource package of space with the itemsadder, but everything was restored after I executed the / iazip command
**Describe the solution you'd like**
Support Space
**Describe alternatives you've considered**
Make a new ItemsAdder Addon?
**Additional context**

**Comment by LoneDev6** [comment]
Hello, I'm already in contact with the Space plugin developer to add support somehow.
Thanks for the patience

**Comment by Klover91** [comment]
is this done? cause i have a HUGE issue with Space connected with IA.

**Comment by LoneDev6** [comment]
@Klover91 
Do not comment on very old issue reports.
This is from a year ago and you're notifying the previous author of the issue report.

>  i have a HUGE issue with Space connected with IA.

This is extremely unclear and it's impossible for me to identify what the issue is.

Anyway you just have to create a new contents sub-folder, and place your extracted space resourcepack inside.
So you'd have: `ItemsAdder/contents/space/resourcepack/assets/...`.
https://itemsadder.devs.beer/plugin-usage/adding-content/contents-folders-structure

Next time if you think it's a bug open a proper bug report on [Github](https://github.com/PluginBugs/Issues-ItemsAdder/issues/new/choose) and provide ALL the information you have to help me reproduce the issue and provide a solution.
If you think it's not a bug (but rather a question on how to configure) you have to use the [forum](https://forum.devs.beer/).
