### ISSUE TITLE
[BUG] Refering to Vanilla textures (minecraft:<.+>) logs 'texture not found', but still uses it

### ISSUE THREAD

**Issue by FokaStudio** [PluginBugs/Issues-ItemsAdder#1142]
**Describe the bug**
Title explains everything

**To Reproduce**
1. Create emoji file with using https://file.coffee/u/ut9zMf7RQB0V-L.yml
2. Do /iareload and look into the console

**Expected behavior**
Vanilla textures appear, but nothing logs into console

**Screenshots**
https://file.coffee/u/xMmhK1ZhdtSLE9.png
https://file.coffee/u/dkS4TDlxuKTANa.png

**Info (please complete the following information):**
```
This server is running Purpur version git-Purpur-1345 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 4e03b8f on ver/1.17.1)
You are 1 version(s) behind
Previous version: git-Purpur-1343 (MC: 1.17.1)
```
 - Client: Vanilla 1.17

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.12
 - LightAPI Fork version: absent (I don't use it due to issues with Tuinity and its forks)
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Additional context**

**Comment by SirCraftypants** [comment]
did you run /iazip before running /iareload

**Comment by FokaStudio** [comment]
yes, I did
I did so like 10 times to confirm the issue, and it was occuring each time I did so

**Comment by LoneDev6** [comment]
Thanks for the report!
This will be fixed in the next update.
ItemsAdder can't find the default vanilla files as they are not in the resourcepack.
I'll ignore the texture file checking if it has `minecraft` namespace.

**Comment by LoneDev6** [comment]
In the new update please don't use "minecraft" as namespace, it can cause issues.
Use the new path method: 
[mcemojis.yml.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/7106925/mcemojis.yml.txt)


Keep in mind that ItemsAdder won't be able to calculate the real image width (real image width is the image width ignoring the transparent pixels).
So you have to fix the scale_ratio manually for each image.

Also note that people may not be using the default Minecraft resourcepack and emojis would look completely messed up because of this.
