### ISSUE TITLE
[BUG] server crashing

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#1146]
**Describe the bug**
If I came to this machine (schematic), the server always crash on purpur, not on the others (tuinity, paper, spigot).
logs: https://discord.com/channels/@me/550357534066868255/881856321828311090
schematic: https://discord.com/channels/@me/550357534066868255/881858418724458527

**To Reproduce**
1. Go to the machine (schem)
2. server crash

**Expected behavior**
the server will not crash

**Screenshots**
![image](https://user-images.githubusercontent.com/29830635/131330686-cc468e28-a398-4b64-8f21-afc44da80a22.png)

**Info (please complete the following information):**
 - Server version: purpur 1.17.1
 - Client version: optifine 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.12
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: example: 4.7.1 b530

**Additional context**
I don't know if this is a direct IA problem, you wanted to send it.

**Comment by LoneDev6** [comment]
## By reading the log:
Seems that for some reason Purpur is calling the BlockPhysics update when ItemsAdder calls this line:
`p.playNote(e.getBlock().getLocation(), Instrument.getByType(instrument), data.getNote());`
Or maybe calls `NotePlayEvent` for some reason, and this creates a chain effect since I'm calling the provided code in a `NotePlayEvent` listener.
This doesn't happen on Paper or Spigot.


## Doing a test:
Nothing bad happens, the "music" plays correctly and no crash happens.

![image](https://user-images.githubusercontent.com/27242001/131884329-0c787bc4-c51b-4e5c-ba2c-a35973364b32.png)


Tested on
```
[18:42:28 INFO]: This server is running Purpur version git-Purpur-1332 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 1105e10 on ver/1.17.1)
[18:42:28 INFO]: You are 38 version(s) behind
```

```
[18:46:37 INFO]: This server is running Purpur version git-Purpur-1370 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cdbf59d on ver/1.17.1)
[18:46:37 INFO]: You are running the latest version
```


## Solution

I have no solution for this issue, I can't manage to trigger it.
Maybe it's something in your config of purpur.yml? You can send it to me if you want.

**Comment by 100petr** [comment]
Yes, it's something with that purpur.yml and it never occurred to me. If I let it regenerate it works normally. https://discord.com/channels/@me/550357534066868255/883667921845489676

**Comment by 100petr** [comment]
Its due blocks.disable-note-block-updates: true

**Comment by 100petr** [comment]
https://github.com/pl3xgaming/Purpur/commit/e444ad7e616ddbcd2827d2f002fb6d7b560cdb3b
