### ISSUE TITLE
[Suggestion] Change the lightapi

### ISSUE THREAD

**Issue by ghtg** [PluginBugs/Issues-ItemsAdder#1182]
**Is your feature request related to a problem? Please describe.**
Currently this warning pops up on paper 1.17.1-233

https://pastebin.com/E6XeJme3

Unfortunately the Staright engine does not support custom lights. Therefore, LightAPI is not compatible with the servers in which StarLight is implemented.

**Describe the solution you'd like**
So in short this plugin is now useless has Paper appears to be using Starlight as well(this since they combined Tuinity). Which, means that any plugins like ItemsAdder, etc had the best start looking for something new. Including me as I was working on a plugin that would have relied on this. Hmmmm. That sucks.

**Describe alternatives you've considered**
It is unlikely that you can find alternatives, the whole light engine is rewritten, which probably means other light plugins will break as well. I dunno what plugin can replace old lightapi.

**Additional context**
I hope a rewrite is underway. Heck, I'd pay for a plugin that fixed this especially now. Because let's be honest clearly StarLight is the new way.

**Comment by FokaStudio** [comment]
Maybe new Light Blocks could be used for this?

**Comment by LoneDev6** [comment]
I'm not the developer of LightAPI.
Anyway seems that original developer of StarLight doesn't care about LightAPI because "Minecraft already has light block".
You can read more here: https://www.spigotmc.org/threads/lightapi-fork.278321/page-10#post-4237787
The only way is to ask LightAPI developer to find a way to fix this, or I'd have to try myself.
Or to ask StarLight developer to add a method to make blocks emit light, just as LightAPI is doing.
LightAPI is not placing a light block, it's setting the actual light emission in a specific set of coordinates.

Sadly the `light` block is not a solution because it's a block, you can't place another block in the same position, even with WorldEdit it will remove the light.


https://user-images.githubusercontent.com/27242001/133645632-a37d5157-c4b0-4551-a3e4-4c069e70b9df.mp4

**Comment by LoneDev6** [comment]
As Quentium stated on my Discord recently:
> The original author of LightAPI pushed some commits 2 days ago, it looks like he's still developing 5.0.0 but it might already have some features implemented
https://github.com/BeYkeRYkt/LightAPI/tree/staging/5.0.0-dev

hopefully we will have it fixed in the next weeks

**Comment by Andre601** [comment]
> As Quentium stated on my Discord recently:
> 
> > The original author of LightAPI pushed some commits 2 days ago, it looks like he's still developing 5.0.0 but it might already have some features implemented
> > https://github.com/BeYkeRYkt/LightAPI/tree/staging/5.0.0-dev
> 
> hopefully we will have it fixed in the next weeks

Stable release is out yet: https://github.com/BeYkeRYkt/LightAPI/releases/tag/5.0.0-Bukkit
