### ISSUE TITLE
[BUG] IAZIP ERROR

### ISSUE THREAD

**Issue by GHsorryiwon12345** [PluginBugs/Issues-ItemsAdder#1199]
**Describe the bug**
Can't zip

**To Reproduce**
1. Do 'iazip'

**Expected behavior**
Error occurs in the console

**Screenshots**
None

**Info (please complete the following information):**
 - Server version: (example: airplane 1.17.1)
 - Client version: (example: optifine 1.17.1)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: (example: 2.4.16)
 - LightAPI Fork version: (example: 3.5.2)
 - LoneLibs version: (example: 1.0.14)
 - ProtocolLib version: (example: 4.7.0)

**Additional context**

LOGS

[2021-09-17-4.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/7187441/2021-09-17-4.log)

**Comment by SNokerYT** [comment]
+1 Same problem

**Comment by HouYanShen** [comment]
+1

**Comment by Litning11** [comment]
+1 also having this issue

**Comment by SNokerYT** [comment]
Also there was another Error on the console after I used --illegal-access=permit
https://paste.md-5.net/acuhocivom.rb

**Comment by LoneDev6** [comment]
![immagine](https://user-images.githubusercontent.com/27242001/133885983-965ea35b-81c9-4584-b720-bbe21469821f.png)
https://discord.com/channels/533407895010803753/534803853049069580/888557250585718794


I will post an update today to avoid this error even if the setting up here is not set.
Anyway you should set it since some other plugins may have similar issues
