### ISSUE TITLE
[BUG] MMOBars assets trouble

### ISSUE THREAD

**Issue by TheAnonim** [PluginBugs/Issues-ItemsAdder#1208]
**Describe the bug**
When I'm insterting assets of MMOBars plugin into ItemsAdder resource-pack folder, this happens (see screenshot). In "hand-made" resource pack all works perfectly

**To Reproduce**
1. Install MMOBars into a server
2. Download MMOBars resource pack
3. Merge MMOBars and ItemsAdder resource packs and let the plugin zip it and automatically upload it
4. See this (screenshot)

**Expected behavior**
Second screenshot is what are normal looking bars

**Screenshots**
![image](https://user-images.githubusercontent.com/39232358/133944107-00ae2859-1fa0-4e02-ac82-9867702c9add.png)
![image](https://user-images.githubusercontent.com/39232358/133944114-80800fce-1624-4bca-9803-e62de0c35de3.png)

**Info (please complete the following information):**
 - Server version: paper-1.16.5-788
 - Client version: vanilla 1.16.4

**Special Info**
 - ItemsAdder version: 2.4.16b
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
I answered a ticket on my Discord server with the same screenshots so I guess you're the same guy.
I close this ticket since we solved

**Comment by TheAnonim** [comment]
I haven't written anything in discord

**Comment by LoneDev6** [comment]
I think because MMOBars is using some characters already used by ItemsAdder, that's why.
I can't really do anything about this, you have to ask MMOBars author to use another namespace for their font or to integrate their system using ItemsAdder API (I'm happy to provide a free copy of ItemsAdder if they ask me): https://github.com/LoneDev6/API-ItemsAdder
