### ISSUE TITLE
Item_frame furniture place on solid item_frame furniture

### ISSUE THREAD

**Issue by TeiBri** [PluginBugs/Issues-ItemsAdder#1293]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Good day. I would like to ask if it is possible to do this so that I can put ITEM_FRAME furniture on ITEM_FRAME SOLID furniture. It would work great, but I'm not sure if it's already in the plugin. I'm a big fan of OriginRealms and I've verified that it's possible. Your plugin is very similar, which we appreciate. :-)

### Is your feature request related to a problem?

Yes. Although I know that it is possible to make SOLID furniture in ARMOR_STAND, but ITEM_FRAME is much better. (At least for me)

### Describe alternatives you've considered

I'm not a programmer, so I don't know how to solve it. But it would definitely be great if it worked. :-)

### Additional context

![2021-11-02_19 48 09](https://user-images.githubusercontent.com/62265168/139926654-12cedb3d-064e-41c8-9cff-d33a33225cae.png)

Here we can see "Tea Setting" (ITEM_FRAME SOLID = FALSE) and "Iron Table" (ITEM_FRAME SOLID = TRUE)
Thanks.

**Comment by LoneDev6** [comment]
Hello, make sure to use armor_stand entity type to create normal furnitures.
item_frame is used to create ceiling/wall placeable furnitures.

I'm sure armor_stand furnitures can be placed one on top of another

**Comment by TeiBri2** [comment]
> Hello, make sure to use armor_stand entity type to create normal furnitures. item_frame is used to create ceiling/wall placeable furnitures.
> 
> I'm sure armor_stand furnitures can be placed one on top of another

(Its my another email)
Thank you for quick response. I'm sure armor_stand can be placed on armor_stand and I appreciate what you do for us, but really isn't there any way to make item_frame furniture go on item_frame (solid) furniture? I know that item_frame is used for wall / ceiling etc. but it is also used for creating tables, lamps, chairs, couches.
Is there really no way to fix it so that item_frame can be placed on that BARRIER?

**Comment by LoneDev6** [comment]
There is no reason to use item_frame as entity type for tables, lamps, chairs etc.
May I know why you really need this feature to be implemented?

**Comment by LoneDev6** [comment]
Because at the time of when I coded the plugin feature I encountered an issue of the Minecraft game itself.
Two item_frame entities cannot be in the same spot, in this case near the same block.
I might find a workaround but at the time of my tests I failed.

I really suggest you to use the armorstand which has absolutely no downside compared to the itemframe.
Also note that itemframes cannot be rotated precisely, only fixed rotations, this is a big downside.
