### ISSUE TITLE
Duplication bug with Essentials recipe book

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#1343]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

pitilon#6950

### What happened?

If EssentialsX and itemsadder are installed, the player writes /recipe diamond_block and takes the item from the recipe book on the left, the diamonds are transferred to his inventory

### Steps to reproduce the issue

1. Install IA, EssentialsX
2. /recipe diamond_block
3. Try to take the item from the recipe book
4. Is in the inventory

### Server version

This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)
[08:54:34 INFO]: You are running the latest version

### ItemsAdder Version

2.4.23

### ProtocolLib Version

4.7.1-SNAPSHOT-b530

### LoneLibs Version

1.0.15

### Screenshots/Videos (you can drag and drop files or paste links)

Without IA:

https://user-images.githubusercontent.com/29830635/144738513-4b1093cd-5cfe-448b-bec7-0473afb78da3.mp4

With IA:

https://user-images.githubusercontent.com/29830635/144738556-d078c217-bfaa-4480-8d35-a29e9c3a017f.mp4

**Comment by LoneDev6** [comment]
I'm afraid I cannot fix this.
I'm sure this `/recipe` feature introduces bugs also in other plugins, not only ItemsAdder.

What they must do is use packets (ProtocoLib) to show these items in the crafting slots instead of really setting items in the crafting inventory.
This is very easy, they just need to send this packet to the client: `PacketType.Play.Server.AUTO_RECIPE` which requires: containerId (get id somehow with NMS) and internal recipe key you want to show.
```java
PacketContainer packet = ProtocolLibrary.getProtocolManager().createPacket(PacketType.Play.Server.AUTO_RECIPE);
packet.getModifier().write(0, containerID);
packet.getModifier().write(1, MinecraftKey.a("minecraft:diamond_sword"));
```

This feature is very dangerous for plugins that allow admins to create custom recipes behaviors and similar.

**Comment by LoneDev6** [comment]
What I can do is intercepting the EssentialsX `/recipe` command and implement my own better logic, that's what I'll do since EssentialsX is a very famous plugin.
