### ISSUE TITLE
Add Custom Crops using Item frames

### ISSUE THREAD

**Issue by kacperleague9** [PluginBugs/Issues-ItemsAdder#1439]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Make a mechanic that will make crops grow (with conditions etc etc) using items on invisible item frames.

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

I don't think there are any.

**Comment by LoneDev6** [comment]
This was heavily discussed on my Discord and I explained why this can't be done.
The amount of lag would be insane.


# Here is my test

GTX 980 Ti which can run all recent games on High/Ultra details.
i7 4790k

## A relatively small farm

### While looking at the entities: 174 FPS
![immagine](https://user-images.githubusercontent.com/27242001/150490984-c5f290b2-a1b0-4dad-8f18-55f108dac23f.png)

### While looking in the opposite way: 316 FPS
![immagine](https://user-images.githubusercontent.com/27242001/150491063-c5c29245-12ea-40ce-a32a-27c292c59351.png)


### Notes
I didn't benchmark the server itself but imagine this on a real server, with multiple floors farms, complete chaos.
I tried using blank ItemFramesjust to show how resource intensive they are.
I highly doubt Minecraft uses Geometry instancing for entities, so each model is rendered in a GPU render pass.
So 1 pass for each ItemFrame and another pass for each item inside of them, instead of 1 pass per entity type/model type and this fills up the rendering pipeline.

This also will cause server lag because of the main entities tick loop, and yes I know you can disable ticking of the ItemFrame but this doesn't "unschedule" their ticking routine from the main loop, their `tick()` function implementation will still get called but won't execute their hanging logic.

You're free to provide benchmarks and your own tests using Oraxen directly, but you'll get the same results or worst (since you'd make the game load items models inside the ItemFrames).

## Summary

I'd avoid adding this feature which would introduce extreme lag.

**Comment by kacperleague9** [comment]
can you check with invisible item frames? maybe they are rendered differently

**Comment by LoneDev6** [comment]
Nothing would change, you can test it if you want

**Comment by LoneDev6** [comment]
## While looking: 282 FPS

![immagine](https://user-images.githubusercontent.com/27242001/150533333-2e67cc5e-d66b-48e9-88c4-7c33b23cfd61.png)

## While not looking: 1223
![immagine](https://user-images.githubusercontent.com/27242001/150533386-c6af4ea6-e52e-43c1-b016-605d34b4d72f.png)

## notes
Imagine this on a gaming laptop or on an average gamer PC.
I sincerely think this is a bad idea and I won't implement this in ItemsAdder.

**Comment by LoneDev6** [comment]
## Two floors little farm: 173 FPS
![immagine](https://user-images.githubusercontent.com/27242001/150533998-5b7775dc-b877-48fc-b16d-d1a96b875280.png)

**Comment by LoneDev6** [comment]
Last note: I'm using this modpack to optimize the game. Imagine not having this.
https://www.curseforge.com/minecraft/modpacks/fabulously-optimized/
