### ISSUE TITLE
I destroy blocks my HAND!

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#1482]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

CrackedLix#3875

### What happened?

see video. https://youtu.be/-qVuBtX96AY

### Steps to reproduce the issue

see video. https://youtu.be/-qVuBtX96AY

### Server version

This server is running Paper version git-Paper-181 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 2121aed)
You are 6 version(s) behind
Download the new version at: https://papermc.io/downloads

### ItemsAdder Version

2.5.5

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.16b

### LightAPI Version (optional)

5.1.0

### FULL server log

No logs.

### Error (optional)

```shell
no error.
```

### ItemsAdder config.yml

```shell
default.
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/-qVuBtX96AY

**Comment by MrJorman** [comment]
I do not know where to write to you, but you are already tired. You have heaps of bugs and 0 functionality, Gust should have told you what you should do and add.

**1. Fix BUG from my VIDEO (UP)**
**2. Fix a visual attribute bug when enchanting an item through an anvil or blacksmithing table.**
**3. Urgently add block hardness for a specific tool so I can specify it in the configs!**
**4. Make an action "play_sound" for a certain event (action) for example I want to use the Chisel mod, I added a chisel to myself, and I want to transform blocks into beautiful blocks by clicking, but the sound works even when I hit. You need to make sure that the sound is attached to the action (event) on replace_near_blocks.**
**5. Finally add "sound_hit, sound_step" for blocks! I want to break blocks, not note blocks!**
**6. Fix freaking silk touch on a spawner or make it possible to specify a drop for a block if it breaks with silk touch, my spawners are broken because of this, I can’t get fragments from them with silk touch!**
**7. Making it so that custom items within frames do not show their names is very inconvenient.**
**8. Finally fix the blocks, I can’t put a hatch on them from above, only from below.**

**THIS ALL!**

**Comment by paulreob** [comment]
+111111111

**Comment by MrJorman** [comment]
> 

Most likely, he is unlikely to fix all this, usually he proves that it should be so, or he will give me a ban because I found too many jambs.

**Comment by MrJorman** [comment]
> +111111111

Most likely, he is unlikely to fix all this, usually he proves that it should be so, or he will give me a ban because I found too many jambs.

**Comment by MrJorman** [comment]
yes. STEP, HIT, FALL - NEED!

**Comment by MrJorman** [comment]
Same for block hardness specification - REALLY NEED!

**Comment by LoneDev6** [comment]
I always try to fix bugs as soon as I can. This week I was very busy working on the ItemsAdder v3.0 update.
I can't spend the time answering tickets and fixing compatibility bugs, this plugin needs new features too.

> Most likely, he is unlikely to fix all this, usually he proves that it should be so, 

This is just disrespectful since I always fix every bug reported, some of them take a lot of time to be identified correctly. To fix a bug I can't just put random code inside the plugin and make a magic, it takes time. I wish a video was enough to fix a problem, as I said I actually have to identify the source of the problem.
Take your time to check my update notes and read how I always publish updates with TONS of bug fixes, I'm not a lazy person nor someone who ignores people on purpose.
https://www.spigotmc.org/resources/73355/updates

> or he will give me a ban because I found too many jambs.

The only reason why I'd ban you is because you're one of the customers which are constantly reporting bugs around the Discord server pinging every staff member and blackmailing with bad reviews. This is the only reason.

Note: You opened this support request at 2AM, how am I supposed to work? While I sleep?
My timezone is clearly noted in the Discord server.

**Comment by LoneDev6** [comment]
Note: avoid using a single Github issue to discuss about multiple already asked feature requests / bug reports.
Use the search button and discuss on the already existing pages.

---------------

Noteblock sounds are clientside not serverside and it's the same sound of all the wooden blocks.

To achieve custom walk/touch sounds I would have to replace the wood sounds with muted sounds so they won't play, then every wooden material will have no sound.
To fix this I'd have to create a new fake sound which is a copy of the original vanilla wooden sound, then play it every time a vanilla event triggers the original wooden sound.
This is just a messy solution and I'd prefer to avoid doing that because it can definitely create confusion to server admins which try to play the wooden sound effect.

Custom walk and touch sounds are a little detail no one will ever notice and requires too much dirty modifications to be added.

In the future I might find a better solution, but I doubt there is since blocks sounds are clientside not serverside.
I always try my best to satisfy the requests but sometimes there is no good way to achieve these ideas.

**Comment by LoneDev6** [comment]
I can't trigger the issue.
Anyway I'll try to add another check, to make sure the break animation is cancelled when you change slot.

https://user-images.githubusercontent.com/27242001/153836011-432b5def-4f3f-4ba6-9986-951fd2a5fba4.mp4

**Comment by LoneDev6** [comment]
Will be fixed in 3.0.0, please read.
![immagine](https://user-images.githubusercontent.com/27242001/156179614-57e63c00-0ac0-47a6-9e70-7074a3a94012.png)
