### ISSUE TITLE
new actions: spawn_mythicmob, spawn_mythicmob_in_sight

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#1526]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Two new actions that would spawn mythicmobs at the player or the players target.

### Is your feature request related to a problem?

yes, I want to spawn a mythicmob with a custom model that will use mythicmob's skill system to despawn itself after a bit, so I can add nice-looking effects to an attack.

### Describe alternatives you've considered

using a command action and placeholders but mythicmobs doesn't have a command for spawning a mob at a player's position

### Additional context

example:
---------------------------------------------------

#spawns a mob at the player
spawn_mythicmob:
  mob: [mob_name]

#spawns a mob at the entity the player is looking at
spawn_mythicmob_in_sight:
  mob: [mob_name]

**Comment by LoneDev6** [comment]
You can use the mythicmobs command to spawn the mob at a particular location.
`/mm mobs spawn -s [mob_name]:<level> <amount> <world,x,y,z,yaw,pitch>` https://git.mythiccraft.io/mythiccraft/MythicMobs/-/wikis/Commands-and-Permissions

You can use `{target-world} {target-x} {target-y} {target-z}` since ItemsAdder will replace them.
These will be replaced on interact, projectile hit, entity damage events.
