### ISSUE TITLE
Vanilla Entities are not getting replaced by custom textures (uploaded to /minecraft/textures)

### ISSUE THREAD

**Issue by RebelDs** [PluginBugs/Issues-ItemsAdder#1765]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

xRebelD#0585

### What happened?

ItemsAdder does not replace replace ENTITY textures properly. I have uploaded the custom textures for vanilla mobs in the  plugins/ItemsAdder/data/resource_pack/minecraft/textures/entity/ path using the proper file structure but textures would not update. Re-zips & server restarts done. No error in console. 

The textures do load properly if the pack is used client-side, so the issue is not on the resource pack side.  

### Steps to reproduce the issue

1. Identify custom textures for vanilla mobs
2. Merge custom textures with ItemsAdder pack (copying and replacing the /minecraft/textures/entity file location)
3. Re-zip using /iazip (no change)
4. Restart the server (no change)

### Server version

This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Purpur-1171 (MC: 1.16.5)

### ItemsAdder Version

ItemsAdder version 3.2.0

### ProtocolLib Version

ProtocolLib version 4.6.1-SNAPSHOT-b501

### LoneLibs Version

LoneLibs version 1.0.18

**Comment by LoneDev6** [comment]
Provide an example pack

**Comment by RebelDs** [comment]
The contents of this pack: https://www.curseforge.com/minecraft/texture-packs/grays-cuter-animals-scarier-monsters have been added to the /minecraft/textures/entity path (correctly). Please let me know whether you'd need me to host the entire ItemsAdder Pack that runs on our server.

**Comment by RebelDs** [comment]
bump

**Comment by thefourcraft** [comment]
# What is this?
IA support model engine and mythic mobs configurations mobs but what you have provided 
doesn't have any concussion to any plugin it's a texture pack?
also if you want to link that texture pack to IA you need to have some knowledge about texture pack merging
> You must have some knowledge on how to create/manage/merge vanilla Minecraft resource packs as this plugin uses a custom-made and modified resource pack to show custom textures/models. 

best way is to get in contact with the creator of the pack and ask him how his texture pack should be merged 

# Copyright
Do note that this texture pack is under "All Rights Reserved unless otherwise explicitly stated." which means that you need to ask permission if you want to use it on your server with another texture pack like IA

# More Info
Please Fill out all the information and provide logs, I can't help you if you want provide logs and info

**Comment by LoneDev6** [comment]
I can read this in the pack page you sent:
![immagine](https://user-images.githubusercontent.com/27242001/174784429-b4913be2-3be5-4c33-8668-15e1389be750.png)
