### ISSUE TITLE
Let items be updated live!

### ISSUE THREAD

**Issue by NoobcoreNetwork** [PluginBugs/Issues-ItemsAdder#2166]
### Describe the solution you'd like

Hey there, I have searched so apologies if the answer is out there but, I love IA, and I want to keep using it, But i'm soon to release some items on my network that might need to be edited in the future, And as far as I'm aware. IA struggles in this department, If i update any lore, item properties etc, The version of the item that the players already have will not be updated, The only solution I have is to switch to mythiccrucible as they can handle this, I'm wondering, is there a specific reason why IA cannot do this? Because It would be an incredible thing that IA is really lacking imo.

### Describe alternatives you've considered

Mythiccrucible

**Comment by LoneDev6** [comment]
Well it's a good idea and it's in my todo list since the first IA version.
The only issue is that it's hard for me to decide what to update and what not.

For example:
- Imagine a custom item configured in a yml file with enchant X and Y.
- Load it ingame, get it via /iaget.
- Now enchant the item using an anvil to add enchant Z.
- Now remove enchant X from the yml file and save it, then use /iareload or restart the server.
- Now enchant the item again using an anvil and add enchant X.
- How can the item know if the enchant X must be removed or not?

I should keep track of changes the various configurations, similar to how git works.
This is very complex.

Another solution would be to simply don't care about mid changes and just remove/add enchants, change lore, change display name of the items which are already crafted with the risk of causing some items to obtain multiple tags.

-----

Let me know if you think about the second solution.

**Comment by Akiranya** [comment]
I would like to share some ideas. They come from the other plugins that already did this.

For what MMOItems did:

*** _This is about how tags are updated (except lore)._

They basically have a revision system and they store an `revision-id` tag on each ItemStack of MMOItems. If the `revision-id` stored in the ItemStack is less than that in the `item config file`, the ItemStack will be updated according to the settings in the `main config file` (which is global, applies to all items).

In the `main config file`, they have the boolean options (not exactly, but similar):

- `revision.keepName`
- `revision.keepEnchantment`
- `revision.keepAttribute`
- ...

So if any of the options are `true`, the corresponding stuff in the ItemStack will leave intact after the ItemStack is updated. If false, the corresponding stuff will just be overwritten (which might be actually enough... and I don't see users of MMOItems suggest a system to deal with the case where LoneDev mentioned above)

For what EcoEchants did:

*** _This is about how lore are updated._

EcoEnchants is purely a plugin that adds more enchantments. But it has a packet-based lore system (the system might be actually implemented in its library plugin: [eco](https://github.com/Auxilor/eco)) - lore is not stored in the itemMeta, instead it is modified when the item packet is being sent to client. With ProtocolLib, this might be possible by modifying this [event](https://github.com/LoneDev6/PacketWrapper/blob/master/PacketWrapper/src/main/java/com/comphenix/packetwrapper/WrapperPlayServerWindowItems.java).

EcoEnchants purely use the system to display the enchantments with dynamic description. So simply reloading the item config files is enough to immediately make new lores effective.

About the downsides: This packet-based lore system might be tricky to implement... since the system has been iterated many times by the author (Fortunately this is open source). Also I could imagine possible confilcits with other plugins which also implemented the packet-based system - might be tricky to figure out the order of lores if multiple plugins try to modify the item packet. Futhermore, the "unsolvable" issue is that ItemStack on the chat are not possible to have lores display correctly - they essentials can't display the lores because the lores aren't stored in the itemMeta, and it might need to modify the chat packet to make it work, which is kinda messy)

Hopefully these ideas are helpful.

**Comment by LoneDev6** [comment]
1. this revision system would break all plugins which interact with ItemsAdder since old items will not match because of that particular tag, I'm sure MMOItems have the same issue. Minecraft is pretty strict on how items match with each other. If a single NBT tag is different then it's not the same item for Minecraft.
2. Packet based lore is easy to do but performance intensive since I have to iterate every inventory item in inventory packets and update them. These packets are sent pretty frequently by the game (inventory click, armor equip, and other events).


So I'd avoid following the route of other plugins.

Btw the main thing to understand is how many times will you update an item? Once in a year because of a mistake? Twice a year because of some rebalancing? Frequently because of some other reasons?

**Comment by Akiranya** [comment]
> 1. this revision system would break all plugins which interact with ItemsAdder since old items will not match because of that particular tag, I'm sure MMOItems have the same issue. Minecraft is pretty strict on how items match with each other. If a single NBT tag is different then it's not the same item for Minecraft.
> 2. Packet based lore is easy to do but performance intensive since I have to iterate every inventory item in inventory packets and update them. These packets are sent pretty frequently by the game (inventory click, armor equip, and other events).
> 
> So I'd avoid following the route of other plugins.
> 
> Btw the main thing to understand is how many times will you update an item? Once in a year because of a mistake? Twice a year because of some rebalancing? Frequently because of some other reasons?

For the first point, actually it's only the plugins that entirely rely on the full itemMeta comparison would break (i.e., they are not calling API of ItemsAdder to check if some item IS a ItemsAdder item when comparing). For plugins that properly call API of ItemsAdder or only check the `namespacedID` of item, it wouldn't be a problem. But yeah I could think of some fully itemMeta based shop plugins would start complaining about it and the players would just find the items are suddenly not saleable to admin shops.

For the sec point, yeah that's also what I'm worrying about..

----

How often updating an item might be due to various reasons... and it would occur more often if the game world tends to last for more than half year. For me, it happens like once a month. The items I created using ItemsAdder are much more stable than those I created using MMOItems. I update MMOItems items mainly because of rebalancing RPG stats

**Comment by LoneDev6** [comment]
This task is very complex to achieve and can lead to an extreme amount of incompatibilities.
I might code some auto updating to forcefully:
- add enchants which are in the yml file and not in the world item but keep enchants that are not in the yml (because users might have enchanted the item)
- update the name and lore (even if this might cause some information to be lost because the lore might have been edited by another plugin)
- I won't update the custommodeldata since itemsadder already ensures that this value is not changed in any way as it has a cache system for this particular reason. Also updating the custommodeldata will break the `replace_properties` [feature](https://itemsadder.devs.beer/plugin-usage/adding-content/item-properties/events/actions#list-of-actions-properties), for example for the [lightsaber](https://github.com/ItemsAdder/OtherPacks/blob/e0205836ed4f5d0da56b21777d11fec1cf8dded4/contents/iaspecial_swords/configs/items/lightsabers.yml) of the default pack.
- I will automatically update the custom (leather) armors color code in case it changed in the yml file to make sure the armors don't have the wrong "worn" texture
- ??? Do you have any other thing in mind?

This feature can be enabled in the config.yml of itemsadder since not everyone will want it for the risk of introducing incompatibilities.

**Comment by Akiranya** [comment]
I guess that's all the thinigs to consider so far.

Might also provide some config options to decide **_when_** to update items, such as when:

1. Picking up an item
2. Joining server (update all items in the inventory)
3. Changing world (same as above)
4. Placing an item in the craft table
5. Moving & draging an item

Some of them may impact the performance but would be convenient
