### ISSUE TITLE
data file completly gone

### ISSUE THREAD

**Issue by jaythepp** [PluginBugs/Issues-ItemsAdder#2167]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Jayman666#9753

### What happened?

items adder lo9ads in resouse but the data file is completly gone
![Screenshot 2022-12-05 122449](https://user-images.githubusercontent.com/111549350/205713455-0029399e-d839-4fd2-8417-5d39bd719a60.png)

### Steps to reproduce the issue

dont knwo how to reduce issue

### Server version

[18:30:33 INFO]: This server is running Paper version git-Paper-296 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: f1583fc)

### ItemsAdder Version

3.3.0 beta r10 version

### ProtocolLib Version

5.0.0 version

### LoneLibs Version

1.0.21 version

### LightAPI Version (optional)

bukkit 5.3.0

### FULL server log

https://paste.sparked.host/duzujaguze

**Comment by LoneDev6** [comment]
I noticed your review, I hope you can remove it since this is not an ItemsAdder bug.

![image](https://user-images.githubusercontent.com/27242001/205913207-b4dfba5e-7ab6-4d88-93e2-a3e0f17ce447.png)

Read there for more information on how the new update works, please read carefully and don't skip: https://itemsadder.devs.beer/3-3-vs-3-2
The new update supports the old data folder anyway, so your old configurations will still load just fine.

ItemsAdder doesn't delete any folder on its own, the data folder is not deleted by ItemsAdder. You probably have deleted it or a staff member did.
