### ISSUE TITLE
Emote f5 and license

### ISSUE THREAD

**Issue by Kokolochnik** [PluginBugs/Issues-ItemsAdder#2244]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

kl1styy's#6069

### Describe the solution you'd like

1) during the playback of emotions on the OriginRealms server, there is a third-person view function. I would like to have the same function.
2) for players who do not have a license, the skin will not be displayed during the playback of emotions, why not make it so that for players who do not have a license, the emotion is not played? but played only when they select their skin using the SkinRestorer plugin

### Is your feature request related to a problem?

They are not here

### Describe alternatives you've considered

They are not here

### Additional context

play.originrealms.com
1.18.2-1.19.2

**Comment by LoneDev6** [comment]
> during the playback of emotions on the OriginRealms server, there is a third-person view function. I would like to have the same function.

You can do that by pressing F5.
ItemsAdder emotes are meant to be used in first person, the head is automatically hidden in first person and shown in third person.

> for players who do not have a license, the skin will not be displayed during the playback of emotions, why not make it so that for players who do not have a license, the emotion is not played? but played only when they select their skin using the SkinRestorer plugin

I don't understand what you mean.
SkinRestorer is mandatory to be used if you're running a cracked server otherwise skins won't be shown.
This might be a bug of SkinRestorer because based on your message seems SkinRestorer is somehow not applying the skin on player join. ItemsAdder is just reading the skin from the gameprofile and SkinRestorer should already write the value there when player joins.

**Comment by Yazerrrr** [comment]
Hey, I was wondering, how can I join the discord server for support.
