### ISSUE TITLE
Text Effects API

### ISSUE THREAD

**Issue by alexanderdidio** [PluginBugs/Issues-ItemsAdder#2256]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Please include Text Effects in the API so that plugin creators can use text effects such as `<r Rainbow>` in their plugins.

Usage example: creating a /rename plugin that allows players to rename items in their hand using `<r Rainbow>`

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

None

**Comment by LoneDev6** [comment]
`/iarename` already supports these effects so you can use it instead.

Sadly there is no easy way to implement an API for that because it uses the Components which are shaded into LoneLibs and you wouldn't be able to access them correctly as it has a different package.

Another thing you can do is read the updated guide in my wiki to use the text effects if you don't have access to "json" components.
https://itemsadder.devs.beer/plugin-usage/text-effects-1.17+#using-them-in-plugins-which-support-legacy-hex-notation
