### ISSUE TITLE
Vehicles can be broken even in protected areas.

### ISSUE THREAD

**Issue by madebygood** [PluginBugs/Issues-ItemsAdder#2292]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

iot#0698

### What happened?

You can destroy other people's vehicles even in areas protected by towny, griefprevention, etc.

Interior items are not destroyed, only vehicles.

On my server, users stole each other's vehicles and terrorized each other.

Needs a fix!

### Steps to reproduce the issue

Just like the description.

### Server version

Current: git-Purpur-1858 (MC: 1.19.2)*
Previous: git-Paper-307 (MC: 1.19.2)

### ItemsAdder Version

3.3.0b-r5

### ProtocolLib Version

5.0.0-SNAPSHOT-b612

### LoneLibs Version

1.0.23

**Comment by LoneDev6** [comment]
There are some worldguard flags to prevent this.
They are useful because people might want to remove other users vehicles from their protected area.
Imagine an user X filling user Y protected are with vehicles just to piss them off. We want user X to be able to remove these vehicles.

https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/worldguard-flags
