### ISSUE TITLE
The converter Atlas (1.19.3) doesn't work

### ISSUE THREAD

**Issue by telfrancesco** [PluginBugs/Issues-ItemsAdder#2404]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

telfrancesco#8158

### What happened?

I have the texture pack for my server in 1.18.2 but in 1.19.3 is bugged, so i have decided to enable the support for atlas in the config.yml but nothing is change..after i tried to execute /iazip and i uploaded the generated file on dropbox nothing is changed..The texture remains bugged..(With texture pink and black on every single texture) 

### Steps to reproduce the issue

1. Enable the atlas support in config.yml
2. execute /iazip in game
3. upload the generated file zip on dropbox
4. execute /iareload and rejoin the server 

### Server version

[20:12:17 INFO]: Checking version, please wait...
[20:12:17 INFO]: Current: git-Purpur-1632 (MC: 1.18.2)*
* You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.4.0b-beta

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.23

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10945199/latest.log)

### Error (optional)

```shell
My client log when i joined the server (after converter)

https://pastebin.com/tSFK6wWb
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/22562779/224405922-cc50a1bb-f2c1-4f2a-8997-9c499a64cad3.png)

**Comment by LoneDev6** [comment]
Delete ALL `auto_generated` folders inside your contents or data folder and run /iazip again.
Also fix models with broken names, for example: `myitems:blocks/Stone_Mossy3`
Uppercase characters are not accepted by the game (since Minecraft 1.9 or so).
I clearly stated it in the wiki (not a limitation of ItemsAdder, it's how the game works).
So for example write `myitems/models/blocks/stone_mossy3` instead.

After you fixed these things please check again your client log and fix the new issues reported by the game if any.
