### ISSUE TITLE
Matching CIT armor fix to armor color instead of itemsadder NBT

### ISSUE THREAD

**Issue by lukipukix** [PluginBugs/Issues-ItemsAdder#2414]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

lukipukix#9718

### Describe the solution you'd like

As I said in title - CIT armor fix uses Itemsadder NBT to match armors. If you can change it to match the armor color instead, this should fix any incompatibility with MMOItems and similar ;)

### Is your feature request related to a problem?

Yes. Problem is that armors took from MMOItems don't work when there is Optifine or CIT mod enabled. They are just leather coloured armors.
![image](https://user-images.githubusercontent.com/98988597/224798860-6c3c73f7-a13b-4bf5-8c29-75089acb09ee.png)
![image](https://user-images.githubusercontent.com/98988597/224798904-f6b9083f-5669-4b04-8b87-f4da8029b28f.png)

### Describe alternatives you've considered

I tried to add Itemsadder NBT tags to MMOItems armor in MI menu but it didn't work.

**Comment by LoneDev6** [comment]
I did a check and I think there is a misunderstanding.
The Optifine configurations has nothing to do with that.
MMOitems auto updating feature is breaking the items because it resets the color to the default value, should be caused by `item-revision` feature of MMOitems.

What you have to do is disable MMOitems items version system or run /iatag while holding a custom itemsadder armor piece, get its color tag and put it also in the MMOitem configuration for your item.

I have no experience with MMOitems so I can't really tell more than that, you could send this issue report to the developer of MMOitems so we can find a solution.
