### ISSUE TITLE
Enhance ores veins generation

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#2435]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

CrackedLix

### Describe the solution you'd like

I want to get very close generation to vanilla.

### Is your feature request related to a problem?

Your plugin has a terrible ore generation

### Describe alternatives you've considered

https://www.spigotmc.org/resources/custom-ore-generator-『1-8-1-19-3』.64339/

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/226363391-b2b46826-5e14-49b9-8093-e13896d6bdaf.png)
simple

**Comment by MrJorman** [comment]
vanilla 
![image](https://user-images.githubusercontent.com/55187962/226363435-36bbc3e1-cbde-407b-af89-a3e39c6d8035.png)

**Comment by LoneDev6** [comment]
Provide screenshots of ItemsAdder "terrible" generation of a single custom block type for me to understand what is terrible.

**Comment by MrJorman** [comment]
check how iron or coal is required in minecraft, blocks of accuracy are separated by cups by veins, and in your case all the ores of 1-2 pieces are scattered all the time in different places!

**Comment by MrJorman** [comment]
terrible ore generation in your plugin, where blocks spawn crookedly one by one

**Comment by MrJorman** [comment]
I can't make an ore vein similar to the generation of an andesite or diorite vein.  yes, even like light dust in hell

**Comment by MrJorman** [comment]
look at the screenshots above, here are the ideal ore generation options, and in your plugin, forgive the full bike

**Comment by MrJorman** [comment]
for example, I created silver ore for myself and I want to make it spawn and its appearance lived like gold ore in minecraft

**Comment by MrJorman** [comment]
and now try to create the same beautiful vein in itemsadder - yeah, you can't!

**Comment by MrJorman** [comment]
Your ore generator is designed and configured for simple-block-generator, for example, making ore as non-zerite scrap - it will work in your plugin.  but there are no ordinary ores with beautiful chunks

**Comment by MrJorman** [comment]
for example, I want to add a new type of stone and I want it to be generated by veins like andesite

**Comment by MrJorman** [comment]
more questions?

**Comment by MrJorman** [comment]
I understand that we will see this innovation from you in a year, or maybe in two - so I'm going in search of a third-party plugin

**Comment by LoneDev6** [comment]
As I asked: Post a clear screenshot of what you don't like about the generation.
Also post the generator yml configuration used so that I reproduce the problem and understand.

I cannot do anything with vague suppositions and random ideas.
Post solid content.

Also avoid using Github like a chat client, I receive 1 notification for each of your messages. My phone was exploding.

**Comment by MrJorman** [comment]
```worlds_populators:
  silver_ore:
    block: caverns_chasms:silver_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    chunk_chance: 50.0
    max_height: 50
    min_height: 0
    vein_blocks: 8
    chunk_veins: 2```

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/226413391-38063c6f-e491-4aa6-a77e-26347afd5b6a.png)

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/226413603-b4c7e445-e35b-43a8-9c88-38b45e6d3b16.png)
ahahaha

```ruby_ore:
    block: caverns_chasms:ruby_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    chunk_chance: 50.0
    max_height: 50
    min_height: 0
    vein_blocks: 6
    chunk_veins: 2```

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/226414002-3edbdf27-fa85-4ac6-b0b7-29d035a49f1b.png)
Are there any questions about generations?)

**Comment by MrJorman** [comment]
I don't see any normal vein-a ore, let's look at vanilla ores generation
![image](https://user-images.githubusercontent.com/55187962/226414543-075ab322-c580-4d7f-9836-5625ba2097a2.png)
![image](https://user-images.githubusercontent.com/55187962/226414858-67cdf093-53bc-4b17-b4a6-eca1ea962751.png)

But why does everything spawn so separately in ItemsAdder?
![image](https://user-images.githubusercontent.com/55187962/226414971-c53ae40c-c8dc-4801-a83e-62fdf8aed87c.png)
![image](https://user-images.githubusercontent.com/55187962/226415133-cbd6e80d-0154-457d-8985-15a307a1cf50.png)
What is this freak? Is it vein?? the ores must all be in contact, and not be in division

**Comment by MrJorman** [comment]
How can you put things in order in the generation of ores? I need the usual generation of ores like in minecraft, it is desirable that I can choose the mode for it: root, glowstone, simple, vanilla

root generation
![image](https://user-images.githubusercontent.com/55187962/226415663-a6344331-e97f-4826-b507-c86327b7872a.png)

glowstone generator
![image](https://user-images.githubusercontent.com/55187962/226415740-a5475d38-535c-4d15-a8fb-5b223c7f66d9.png)

simple dimple
![image](https://user-images.githubusercontent.com/55187962/226415793-65dcc787-470c-4296-88f4-1e4603d786d3.png)

vanilla (DEFAULT) (BAZA)
![image](https://user-images.githubusercontent.com/55187962/226415833-95077ba7-4bcb-4b82-83f4-94163e910640.png)

**Comment by MrJorman** [comment]
Oh my god, you still haven't fixed the spawner with silk touch!!! Ahah

**Comment by MrJorman** [comment]
I can't get spawner fragments if I break it with silk touch, but if I include your function in the configuration, then without silk touch I don't get fragments, is it really so difficult that I can get fragments with and without silk touch?

**Comment by LoneDev6** [comment]
Why not contacting the other plugin author instead of spending a whole day ignoring my messages and spamming this thread with 20+ messages one near the other?

I added ItemsAdder license for free to the developer of **Custom Ore Generator** plugin.
![image](https://user-images.githubusercontent.com/27242001/228857609-03a6fe60-c532-4a7d-9eb3-f84143ab008c.png)

They can use the ItemsAdder API to spawn blocks, it's well documented and contains all the needed methods to spawn blocks.
Make them aware of that.
https://itemsadder.devs.beer/developers/java-api/examples#custom-blocks-docs
https://github.com/LoneDev6/API-ItemsAdder/blob/master/src/main/java/dev/lone/itemsadder/api/CustomBlock.java

-------

At some point I will rework on the ores generation. I already have scheduled some ideas for a better generation., for example new shapes. https://github.com/PluginBugs/Issues-ItemsAdder/issues/1280

The default items adder pack was tested for MONTHS to see if an ore is hard to find or easy to find and it's very balanced.
https://youtu.be/q2eabTfnT_k

Changing how ores are spawned will mean to break every server who already configured custom ores and calculated the chance of finding ores.

If you want to increase the amount of ores per vein you have to play with values until you find a good configuration.
In my examples I set low values because the world is now very big in 1.19 and finding ores is too easy. That's why veins are smaller in my default pack.
