### ISSUE TITLE
resource pack doens't ask to be applied when logging in for players

### ISSUE THREAD

**Issue by SaltyNickJr** [PluginBugs/Issues-ItemsAdder#2468]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

SaltyNick#9491

### What happened?

I have tried to reload the plugin with /iareload and I have tried rezipping the file by doing /iazip. It works for me (the owner) but for members and ranks it seems to not work. I have also tried doing /iatexture and nothing loads up even for me. Not sure why this is happening.

### Steps to reproduce the issue

1. log in.
2. Doesn't ask for texturepack download.
3. I tried relogging nothing happens.

### Server version

3 14:09:45 [Server] [INFO] This server is running Paper version git-Paper-"38be4f8" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 38be4f8)
28.03 14:09:45 [Server] [INFO] You are 7 version(s) behind
28.03 14:09:45 [Server] [INFO] Download the new version at: https://papermc.io/downloads
28.03 14:09:45 [Server] [INFO] Previous version: git-Paper-"155aa36" (MC: 1.19.3)

### ItemsAdder Version

ItemsAdder version 3.4.1-r3

### ProtocolLib Version

https://gyazo.com/a06ec57936bf7e0ab16326084788f57d

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

https://mcpaste.io/4b654a540fd976a6

**Comment by LoneDev6** [comment]
Please check here and let me know.
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown#my-players-cant-see-textures-but-ive-followed-the-whole-tutorial

- If your players can't see the new items just link them this simple screens to fix it! http://imgur.com/a/SG0AU​
- If you still have problems delete the server from your servers list, add it again and then accept resource packs.
- If you still have problems leave the server, go to %appdata%/.minecraft/server-resource-packs and delete everything. Then join the server again.
Make sure you don't have any inventory (GUI) or book opening on join.
This can cause the resourcepack prompt to disappear and the player won't be able to click on it.
In order to fix this you can use the free plugin [ResourcePackBroadcast](https://www.spigotmc.org/resources/resourcepackbroadcast.88318/). This allows you to run commands as soon as the resourcepack is accepted (and various other features).
You can also try increasing the delay-ticks in config.yml of ItemsAdder to 10 or greater.
