### ISSUE TITLE
Text effects on emojis

### ISSUE THREAD

**Issue by ThePuffle** [PluginBugs/Issues-ItemsAdder#2483]
### Discord tag (optional)

Puffle#9411

### Describe the solution you'd like

Animated emojis using core shaders similar to this (Ultra) Tag. https://imgur.com/a/Rvq3MH4 I think it is possible but unsure how much of a workload it would be to make it accessible. 

### Is your feature request related to a problem?

Lack of animated emojis for custom images. 

### Describe alternatives you've considered

Core shaders are possible to implement this but i would like a more accessible way to do this.

**Comment by LoneDev6** [comment]
Currently you can do it via text effects, but ItemsAdder currently doesn't allow that on emojis if I recall, but you can try.
https://itemsadder.devs.beer/plugin-usage/text-effects-1.17+

**Comment by LoneDev6** [comment]
Done, now you can use text effects on font images (in this example an emoji)

## Limitation

It works only if the full message is wrapped into a text effect, otherwise it won't work.


`<rw hello this is a test :smile: with emoji> test message`
![Image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/c84e8f45-57ed-49fa-a3ea-5701f0e44027)



## Example

`<rw hello this is a test :smile: with emoji>`

https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/b856e9a1-1202-4342-b05c-2f021ebeb93d
