### ISSUE TITLE
API to retrieve resource pack URL

### ISSUE THREAD

**Issue by LOOHP** [PluginBugs/Issues-ItemsAdder#2484]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

LOOHP#6007

### Describe the solution you'd like

It would be great if there is an API available to retrieve the resource pack URL without waiting for a ResourcePackSendEvent.

### Is your feature request related to a problem?

N/A

### Describe alternatives you've considered

Currently, without the API, I did put together a [**hacky solution**](https://github.com/LOOHP/InteractiveChat-DiscordSRV-Addon/blob/master/src/main/java/com/loohp/interactivechatdiscordsrvaddon/hooks/ItemsAdderHook.java). Much better if there is an API for this.

### Additional context

N/A

**Comment by LoneDev6** [comment]
What you're doing is cool but not safe because these names will surely change between builds of the plugin.

What you can do is open config.yml of itemsadder and check the hosting method enabled.

If it's auto external you can read the url from this file (if exists): `plugins\ItemsAdder\storage\cache\various\auto_external_host.yml`

If it's self host you can get the IP and PORT from the config.yml file itself and the URL will be: `https://<IP>:<port>/generated.zip`

If it's external host you can get the IP and PORT from the config.yml file itself.

----

In a future update I'll add the API method requested, but please do not use reflection as it's not reliable between updates.

**Comment by LOOHP** [comment]
Well in that case I'll wait for your API method. Thank you!

**Comment by LOOHP** [comment]
Oh, I thought that was the sha1 hash of the resource pack. Does ItemsAdder send hashes to players to verify pack downloads? If so, is there a way to get that as well?

**Comment by LoneDev6** [comment]
Hash is just broken in Minecraft so I'd continue avoiding to use it if I were you.
https://bugs.mojang.com/browse/MC-164316

It's the hash of the file.
Get the string and split by `#`.

**Comment by LOOHP** [comment]
Alright, I could work without the hash, just asking. Thank you for the information.
