### ISSUE TITLE
Can't load in 1.18.1 server

### ISSUE THREAD

**Issue by YouMing233** [PluginBugs/Issues-ItemsAdder#2491]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

For some necessary reasons, I can‘t update to version 1.18.2
Although I set ignore-server-compatibility-check to true, the plugin still does not work properly
How can I make ItemsAdder to work on the 1.18.1 server?

Or what is the final version of ItemsAdder that will work on the 1.18.1 server?

### Steps to reproduce the issue

when I starting the server

### Server version

Current: git-Purpur-1566 (MC: 1.18.1)*

### ItemsAdder Version

ItemsAdder version 3.4.1-r4

### ProtocolLib Version

ProtocolLib 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLib version 1.0.24

**Comment by LoneDev6** [comment]
The plugin is not compatible with 1.18 and 1.18.1, you have to install 1.18.2.
Using an old version of the server is not a good idea for security, stability and functionality.
If you have a plugin which is not updated to work on 1.18.2 you should really ask the developer to update the plugin because it has no sense to stay on 1.18.1.

> Or what is the final version of ItemsAdder that will work on the 1.18.1 server?

`3.0.0-beta7`, but you should really not install it since it's a very old version of ItemsAdder which has issues which were fixed in the next versions.
Never use outdated plugins or server versions, it just is a way to get issues.
