### ISSUE TITLE
Resource pack infinitely loading.

### ISSUE THREAD

**Issue by ChefJisoo** [PluginBugs/Issues-ItemsAdder#2517]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Chef Jisoo#7199

### What happened?

Hi! For months now, we've had players with their resource pack (we self host) infinite load upon joining. We have finally found a common link in that everyone affected has played on their account, the pack has worked fine. Then for whatever reason, they'd get a new laptop/pc, try play on that and have the pack reload infinitely.

### Steps to reproduce the issue

No other way I can describe it other than getting a brand new laptop, and trying to download the pack.

### Server version

1.18,2

### ItemsAdder Version

The /version command does not work, however it is the most recent version added to the website as of 08/04/2023

### ProtocolLib Version

The /version command does not work, however it is the most recent version added to the website as of 08/04/2023

### LoneLibs Version

The /version command does not work, however it is the most recent version added to the website as of 08/04/2023

### FULL server log

You can find it in my previous issue.

### Other files, you can drag and drop them here to upload. (optional)

https://github.com/PluginBugs/Issues-ItemsAdder/issues/2475

**Comment by ChefJisoo** [comment]
Hello? Are we going to get any help?

**Comment by LoneDev6** [comment]
I explained it hundred of times. It depends on the GPU of the computer. It's not happening to everyone because every GPU has its own limit.

Read here: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/resource-pack-help/3147978-1024x-pack-failing-to-load#c13

![image](https://user-images.githubusercontent.com/27242001/231424313-69ac749b-7e7a-497c-84aa-01f5cdd04cd7.png)

![image](https://user-images.githubusercontent.com/27242001/231424349-a0f43ddc-7899-4b32-b2f3-ae238bc92c0a.png)

It's like each time I send you the correct explanation about the issue you erase your memory and re-ask it again and again.
Please read that carefully and fix your resourcepack. This has NOTHING to do with ItemsAdder itself, it's how the game works. You would have the SAME exact issue with ANY custom resourcepacks management plugin.
