### ISSUE TITLE
Default Join and Leave Message not working after removing resourcepackbroadcast?

### ISSUE THREAD

**Issue by 5H08** [PluginBugs/Issues-ItemsAdder#2549]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Following the tutorials on the wiki, I installed resourcepackbroadcast and placeholder API hoping to clear out a potential conflict of resources with skinrestorer. However, then I figured out the issue is on the host, and removed the two plugins due to player names not displaying on join, the color code not applying, and a significant lag between player joining and the message showing up. My vanilla on join message then completely stopped working.

### Steps to reproduce the issue

1. Install ResourcepackBroadcast and Placeholder API
2. Remove the plugins

### Server version

1.19.3

### ItemsAdder Version

3.4.1

### ProtocolLib Version

4.8.0

### LoneLibs Version

2.6

**Comment by LoneDev6** [comment]
There is no need to ping me, I always receive a notification for each message.
Thanks for the patience.

> due to player names not displaying on join

No idea what you mean the plugin replaces `%player_name%` even if you don't have PlaceholderAPI installed.
This is very strange.

> the color code not applying

About colors I can fix that by adding [adventure](https://github.com/KyoriPowered/adventure) support and simple legacy `&` colors support.

> and a significant lag between player joining and the message showing up.

The plugin shows the join message when the player correctly downloads the resourcepack, this is the cause of the delay, to avoid seeing player join when they are still loading the pack.


> My vanilla on join message then completely stopped working.

This is not related to ItemsAdder nor to ResourcePackBroadcast because none of them edit any configuration or special flag of the server to disable messages.
If you uninstall ResourcePackBroadcast you won't get any leave message cancelled simply because the plugin is not cancelling them anymore as it's uninstalled.
On the other hand join messages won't appear anymore because you have disabled them from EssentialsX plugin or some other plugin you use to get join messages.
