### ISSUE TITLE
Support for RecipeManager2 plugin

### ISSUE THREAD

**Issue by Reeferx7** [PluginBugs/Issues-ItemsAdder#2559]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Hello, can you add support to plugin https://github.com/haveric/RecipeManager2

it has almost everything about recipes and right now doesn't work.

### Is your feature request related to a problem?

The problem is when I create a new recipe with RecipeManager2 and use itemadders items doesn't work don't display the crafting result.

### Describe alternatives you've considered

-

**Comment by LoneDev6** [comment]
You have to ask the developer of the recipes plugin to get in touch with me using this Github page so that we can work together to find a solution.
For example I worked with the developers of [CustomCrafting](https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/customcrafting#how-to-use) and [Recipe Control](https://www.spigotmc.org/resources/recipe-control-%E2%9C%AE-edit-and-create-recipes.67216/) to add compatibility.

**Comment by haveric** [comment]
RecipeManager dev here. What's the best way to communicate with you on this @LoneDev6 ?

**Comment by LoneDev6** [comment]
You can share information here.
I'd like to get more information on what is broken. Videos and configurations will be good to understand the issue better.

**Comment by LoneDev6** [comment]
I need some methods to know if a custom recipe is added by RecipeManager2.
`public boolean isRecipeManagerRecipe(PrepareItemCraftEvent e)`
`public boolean isRecipeManagerRecipe(FurnaceSmeltEvent e)`
`public boolean isRecipeManagerRecipe(PrepareAnvilEvent e)`

This is how I added CustomCrafting plugin compatibility.
