### ISSUE TITLE
Custom blocks are turning into vanilla blocks 

### ISSUE THREAD

**Issue by aaa8881** [PluginBugs/Issues-ItemsAdder#2602]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

signition#0001

### What happened?

custom block is keep becoming vanilla block.

customcrop's "pot" which is noteblock is turning into noteblock
customcrop's greenhouse which is chorus fruit is turning into chorus fruit.

### Steps to reproduce the issue

this is unsure , but sometimes happen. 
with more than 300 cases  ( I'm not exaggerating. we did examine this much cases ) , I really couldn't find particular pattern. 

### Server version

pufferfish 61 ( paper 1.19.3 fork )

### ItemsAdder Version

3.4.1-r6 
( I know this is not latest, but I dont see any relevant changes in latest version )

### ProtocolLib Version

#616

### LoneLibs Version

1.0.24

### FULL server log

no particular relevant log

### Error (optional)

```shell
[ItemsAdder] [m[0;33;1mError loading world 'fixed_glitched_blocks.pregion' file. Regenerated: /app/live/minecraft/survival/./world/itemsadder/region/fixed_glitched_blocks.pregion[m

I enabled block log, but this is only thing I could find in log ,
but actual glitch happens much more often
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://cdn.discordapp.com/attachments/1101348058257698936/1104015409776185364/5b4f2ae2c6def4cc.mp4

well.. this is cdn , so will download a short video.

**Comment by aaa8881** [comment]
just to make sure ... please don't say , "it shouldn't be happening" 
we're literally encountered this more than 10k times ( not kidding ) with 1400 concurrent players Many people just accept , some are raged and stuff. it does happen, and quite often.

**Comment by Xiao-MoMi** [comment]
I think the problem is likely due to high concurrency tasks, where there is an issue with custom block data storage. Because as seen in the video, the model of the block is normal, which indicates that the correct block has been placed when using the IA API. But when the player interacts, it changes back to the note box, indicating that the data of the IA block has been corrupted.

Here are the codes related to IA in CC
https://github.com/Xiao-MoMi/Custom-Crops/tree/main/src/main/java/net/momirealms/customcrops/api/customplugin/itemsadder

As you can see, I use IA's API to implement these block operations, rather than changing the tone and timbre of the noteblock.

According to the previous issue similiar to this, the common that can be found is that there are many players on the server, which also means that there are more custom blocks, and more crop blocks as well. I personally think that the reason why it was not possible to reproduce before was because the concurrency of the operation was not high enough.

**Comment by aaa8881** [comment]
Xiao-MoMi's patch has actually mitigated frequency of issues. I think he's getting correct point.

**Comment by LoneDev6** [comment]
This is not clear, are the custom blocks handled by an external addon using the ItemsAdder API or not?
How are they placed?
To place custom blocks using Java you have to rely on the ItemsAdder API. You cannot place them blockdata using Spigot API or it won't last.


![Image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/7746c6a8-3c52-4236-811e-822a24481b66)


> Xiao-MoMi's patch has actually mitigated frequency of issues. I think he's getting correct point.

Which "patch"? This is not clear.

> just to make sure ... please don't say , "it shouldn't be happening"
we're literally encountered this more than 10k times ( not kidding ) with 1400 concurrent players Many people just accept , some are raged and stuff. it does happen, and quite often.

I'd love to have the magic wand and fix everything but I can fix stuff only if we manage to find a proper proof of concept on how to reproduce the issue.
Right now the current blocks system was tested for MONTHS before release and was working fine.
We have to find a proper way to reproduce the issue so that I can fix it.

**Comment by LoneDev6** [comment]
Anyway this ticket is a duplicate of this one: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2403
Please do not open multiple reports for the same issue.
