### ISSUE TITLE
Cant use Custom Texture in DeluxeHub3

### ISSUE THREAD

**Issue by OffVeron** [PluginBugs/Issues-ItemsAdder#2603]
Hello,

I can not use custom textures in DeluxeHub3 plugin, does anyone know how to enter the "material:"?

**Comment by LoneDev6** [comment]
You have to ask the developer of DeluxeHub3 to add ItemsAdder support.
The API is public and it's documented, they just have to read it.
They can also just add CustomModelData support so that you can manually set it in DeluxeHub3.

The CustomModelData of a custom item can be obtained by using the command /iacustommodeldata <item-name>`
