### ISSUE TITLE
Lag on call of MinecraftComponentSerializer#deserialize() method

### ISSUE THREAD

**Issue by bridgelol** [PluginBugs/Issues-ItemsAdder#2683]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Bridge#1353

### What happened?

Experiencing lag spikes due to the MinecraftComponentSerializer#deserialize() method being called

### Steps to reproduce the issue

Use the plugin

### Server version

Pufferfish version git-Pufferfish-"47c34ca" (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT)

### ItemsAdder Version

3.4.1c

### ProtocolLib Version

5.0.0-SNAPSHOT-b612
(Shouldn't matter)

### LoneLibs Version

1.0.24

### FULL server log

No logs, performance issue causing lag spikes

### Screenshots/Videos (you can drag and drop files or paste links)

![spark-itemsadder](https://github.com/PluginBugs/Issues-ItemsAdder/assets/29434554/c2ad6f90-83bd-43b9-9e6d-7431e3bde5c1)
![spark-lonelibs](https://github.com/PluginBugs/Issues-ItemsAdder/assets/29434554/22dc5053-e6dd-416f-8a44-964a1cdda74d)

**Comment by LoneDev6** [comment]
This is due to the fact that on Minecraft 1.19.4 I have to use Adventure API to handle `ClientboundPlayerChatPacket` packet component text to replace emojis in chat and its performance seems not very good on a large amount of messages sent each second.

What you can do is disable emojis completion in chat:
```yml
font_images:
  chat:
    enabled: false
```
Another solution (the better one) is to install a chat plugin which allows you to add some cooldown to messages, since this issue happens only on servers where people are writing a lot in chat.

**Comment by bridgelol** [comment]
This seems to be the cause of our server experiencing lag spikes, ~150 concurrent players.

Spark report made by using the --only-ticks-over flag and 1500 as value.

**Comment by bridgelol** [comment]
Sounds good! Thanks for the amazing work.
