### ISSUE TITLE
Missing textures help

### ISSUE THREAD

**Issue by hadoken12** [PluginBugs/Issues-ItemsAdder#2700]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I have some white figures under the tool bar (guess it's gui bug) and one missing texture in ai menu

### Steps to reproduce the issue

1. join to server
2. done

### Server version

[System] [CHAT] This server is running Paper version git-Paper-545 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bacbf86)\nYou are running the latest version

### ItemsAdder Version

21:27:11.501
[System] [CHAT] ItemsAdder version 3.4.1e
21:27:11.501
[System] [CHAT] Customized Minecraft without client mods!
21:27:11.501
[System] [CHAT] Website: devs.beer
21:27:11.501
[System] [CHAT] Author: LoneDev

### ProtocolLib Version

21:27:37.350
[System] [CHAT] ProtocolLib version 5.1.0-SNAPSHOT-645
21:27:37.350
[System] [CHAT] Provides read/write access to the Minecraft protocol.
21:27:37.350
[System] [CHAT] Authors: dmulloy2 and comphenix

### LoneLibs Version

21:27:58.755
[System] [CHAT] LoneLibs version 1.0.24
21:27:58.755
[System] [CHAT] Collection of libs used by my plugins
21:27:58.755
[System] [CHAT] Authors: LoneDev and others

**Comment by LoneDev6** [comment]
Include ALL information you have in order to let me identify the issue.
Send also screenshots of the issue.
It's impossible for me to help you without any information about the problem

**Comment by hadoken12** [comment]
what you want me to do? paste a log and screenshot of how it looks like?

**Comment by LoneDev6** [comment]
> Anyway this seems to be a support request other than a bug report.
Please read here https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown
This guide is made to help everyone to understand why something is not loading correctly and it's the only way to identify the issue.
I cannot do it remotely since every server has a different setup.

If you still have the issue even after carefully reading my previous explanation please provide screenshots of the issue.

**Comment by hadoken12** [comment]
i have done everything and still nothing, i will just use oraxen

pt., 16 cze 2023 o 15:58 LoneDev ***@***.***> napisał(a):

**Comment by LoneDev6** [comment]
You can use any plugin you want, but if you misconfigure the plugin you'll always get broken models and textures ingame.
The important thing is first find out why the textures and models are not loading, so you understand the cause and stop doing the same mistake, it's important to understand how resourcepacks work in order to avoid this kind of issues.
I'm sure you'll experience similar issues with Oraxen or any other resourcepack manager plugin, not only ItemsAdder.


Anyway the trick, as I said in the guide, is to read the CLIENT log which contains precise information of why and what is misconfigured.
By the way ItemsAdder detects most errors in configurations and already reports them in your SERVER log, so it's a very powerful tool to easily identify the issues without the need to read the client log.

Let me know if I can further assist you.
Have a nice week.
