### ISSUE TITLE
Overload and tps drop

### ISSUE THREAD

**Issue by ccyounga** [PluginBugs/Issues-ItemsAdder#2752]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

ccyounga

### What happened?

Hello. I can't tell you anything, just take a look at the timings reports:
https://timings.aikar.co/dev/?id=a84b7106f7ad4bfbb7e8fada4563b457
https://timings.aikar.co/dev/?id=9519689cbec84e0d9ee77ab665451cd5#timings

### Steps to reproduce the issue

tps
timings on
timings paste

### Server version

Paper version git-Paper-386 (MC: 1.18.2)

### ItemsAdder Version

3.4.1f2
I can't use the newest one, because the fix-packet-too-large function is broken in one of the plugins, the players are not allowed to the server, I returned the older versions of the plugins (itemsadder, protocollib, lonelibs). I'll wait for a fix.

### ProtocolLib Version

4.8.0
I can't use the newest one, because the fix-packet-too-large function is broken in one of the plugins, the players are not allowed to the server, I returned the older versions of the plugins (itemsadder, protocollib, lonelibs). I'll wait for a fix.

### LoneLibs Version

1.0.25
I can't use the newest one, because the fix-packet-too-large function is broken in one of the plugins, the players are not allowed to the server, I returned the older versions of the plugins (itemsadder, protocollib, lonelibs). I'll wait for a fix.

### FULL server log

There is nothing in it.

### Error (optional)

```shell
No.
```

### Problematic items yml configuration file (optional)

```shell
No.
```

### Other files, you can drag and drop them here to upload. (optional)

No.

### Screenshots/Videos (you can drag and drop files or paste links)

[img]https://i.imgur.com/r1wdBA6.jpg[/img]

**Comment by LoneDev6** [comment]
> because the fix-packet-too-large function is broken in one of the plugins

What do you mean exactly? I don't understand.


Anyway based on your report you can try to disable these options in config.yml of ItemsAdder.
```yml
  convert-vanilla-blocks:
    enabled: false
```

```yml
  fix-glitched-blocks:
    enabled: true
```


Also most part of this timings report is used by the assets loading phase which was already fixed in some old updates.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2649

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/153f6963-ef73-4156-b24d-03ebd8b4b0c0)


Another note: you're generating the reports in the wrong way.
You must not generate timings reports at the start of the server. You have to let it run for like 30-60 minutes THEN generate the report (the more the better).
Reports generated on the first minutes after server startup are not reliable because most heavy calculations happen at the server start, so obviously you will get bad performance in the timings report.

**Comment by ccyounga** [comment]
The first report was not at the start. Disabled except that "fix-glitched-blocks:", the other parameter was already disabled.
I would like to note all the same that fix-packet-too-large is broken, the latest version does not allow you to enter the server.

**Comment by LoneDev6** [comment]
Please can you add more info about the `fix-packet-too-large` issue?
Provide the screenshot of the CLIENT error you get when joining, the one you get when kicked.
If possible please also get the CLIENT log (not server, I need the CLIENT log in this case) of when you get kicked.
You can read here how to get the client log, it's very easy: https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown#original-launcher

Also provide the complete server log of when the kick issue happened.

Please do it HERE in this new Github thread, since having multiple reports in the same thread is not a good thing to organize updates: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2774

**Comment by LoneDev6** [comment]
> The first report was not at the start

Okay but it triggered the ItemsAdder reload event, probably because of /iazip or /iareload.
This trigger the items/assets reload and it's heavy in older versions of the plugin.
As I said this was fixed in an old update.
More info: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2649#issuecomment-1561665837
