### ISSUE TITLE
Resource pack is not prompting new players

### ISSUE THREAD

**Issue by ubdeadhaha** [PluginBugs/Issues-ItemsAdder#2797]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

freezin_

### What happened?

When players join the server for the first time, they are not prompted with the resource pack. This causes a lot of confusion and ultimately disconnects. 

### Steps to reproduce the issue

1. Join a server for the first time as a new player

### Server version

Papier 1.19.3-448

### ItemsAdder Version

3.5.0b

### ProtocolLib Version

5.1.0-SNAPSHOT-654

### LoneLibs Version

1.0.25

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11827056/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

![Screenshot (473)](https://github.com/PluginBugs/Issues-ItemsAdder/assets/125194180/d245c128-d3db-44da-81c9-4db7332dfc51)
![Screenshot (471)](https://github.com/PluginBugs/Issues-ItemsAdder/assets/125194180/c3ea5084-0bb8-47ca-ad0e-1890e78f7449)

**Comment by ubdeadhaha** [comment]
Here is my config.yml : https://pastebin.com/hJZBuCX3


    self-host:
      enabled: true
      server-ip: 104.238.222.34
      pack-port: 8673
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true

**Comment by LoneDev6** [comment]
Increase the delay of the pack, in config.yml
Set it to like 40.

https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown#my-players-cant-see-textures-but-ive-followed-the-whole-tutorial

> Make sure you don't have any inventory (GUI) or book opening on join.
This can cause the resourcepack prompt to disappear and the player won't be able to click on it.
In order to fix this you can use the free plugin [ResourcePackBroadcast](https://www.spigotmc.org/resources/resourcepackbroadcast.88318/). This allows you to run commands as soon as the resourcepack is accepted (and various other features).
You can also try increasing the delay-ticks in config.yml of ItemsAdder to 10 or greater.

**Comment by ubdeadhaha** [comment]
Will do, thanks! BTW, what an amazing plugin!

**Comment by LoneDev6** [comment]
Thanks! I try my best :D
