### ISSUE TITLE
New custom ui elements and more easier

### ISSUE THREAD

**Issue by Mathildeuh** [PluginBugs/Issues-ItemsAdder#2898]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

mathildeuh

### Describe the solution you'd like

A better and easier way to add custom HUD with plugins or only itemsadder

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

Complex plugin like RPGHud

**Comment by LoneDev6** [comment]
I don't really understand what you mean exactly.
Complex GUIs like RPGHuds are not really possible to be implemented more automatically because they require some custom logic to be coded.
RPGhuds also implements some optimizations which aren't possible to be implemented using the ItemsAdder built-in HUDs configurations.
