### ISSUE TITLE
Rescue server for pack load

### ISSUE THREAD

**Issue by WarnDa** [PluginBugs/Issues-ItemsAdder#2973]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

warnd

### Describe the solution you'd like

Add an option to set a rescue method if packs URL fails to load for a player.
It allows ItemsAdder to select a second URL/Method if the website where your pack is hosted is getting inaccessible/to slow.

### Is your feature request related to a problem?

It happened me twice in 8 months, where the website where the pack is hosted was inaccessible for 10mn, but during this time players couldn't connect, and when you are at work it's a pain, and it can happens to everyone

### Describe alternatives you've considered

Don't get a website that could get issue ?

**Comment by LoneDev6** [comment]
This won't really work well since I would have to try to download the resourcepack from the server each x minutes to make sure it's still reachable. This will introduce unnecessary traffic.
This would still open up some players to the issue since the pack might not reachable during the delay of the "ping" logic I cited before.

Anyway your resource server should not really be unreachable ever, there is something wrong with your hosting provider, I'd change it.
