### ISSUE TITLE
DisplayEntity CustomBlock!!!

### ISSUE THREAD

**Issue by IPECTER** [PluginBugs/Issues-ItemsAdder#3009]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Make CustomBlock using DIsplayEntity!!!

### Is your feature request related to a problem?

Unlimited and More Easy way for making CustomBlock

### Describe alternatives you've considered

~~Oraxen already has this~~
I believe that you can implement!

**Comment by LoneDev6** [comment]
Display entities are not meant to be used to make custom blocks.
They will create intense lag since they are entities rendered in a single render pass, so your game will lag like crazy if you have a chunk filled with custom blocks.

It's not necessary a good thing if another plugin implements a feature.
I don't personally thing it's a good idea to implement something that it's flawed to begin with.
