### ISSUE TITLE
`replace_block` not recognizing id, only namespace+id

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3029]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/3015#issuecomment-1725582980

`replace_block` not recognizing id, only namespace+id.

**Comment by ShizuArt** [comment]
Wow, something weird just happened
I wanted to look into this problem again, so I retested several times with my basic config, the one I had before the last update which fixed this and and which I had never modified since. It didn't work
I replaced `escargot` with `STONE`, it worked
I thought that was weird, so I thought maybe I should add the namespace. I did it and it worked
And just now, I tested again without the namespace and it works
