### ISSUE TITLE
Please add a parameter to disable autoloading _iainternal

### ISSUE THREAD

**Issue by shiksyt** [PluginBugs/Issues-ItemsAdder#3037]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

sh1kcs

### Describe the solution you'd like

Add the ability to disable autoloading _iainternal

### Is your feature request related to a problem?

Due to the set of resources _iainternal, our tab with the picture does not work

### Describe alternatives you've considered

They are not here

**Comment by LoneDev6** [comment]
I'm sure it's not caused by `_iainternal` as they work fine.
Please refer to this guide to know the cause of the issues: https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

Anyway there is already an option, disable it and run /iazip to regenerate the resourcepack.
`extract_internal_utility_assets: false`
