### ISSUE TITLE
Update: I have reorganized my folder and it has fixed.

### ISSUE THREAD

**Issue by sysadmin-jesus** [PluginBugs/Issues-ItemsAdder#3137]
Update: I have reorganized my folder and it has fixed.

_Originally posted by @PhiberOptik23 in https://github.com/PluginBugs/Issues-ItemsAdder/issues/2877#issuecomment-1636451370_

            Hi, I have the same problem as him, but I don't understand what he means by "Organize folders".

**Comment by LoneDev6** [comment]
This is probably caused by a misconfiguration of the plugin, so how folders are structured and where files are put.
It's impossible for me to identify the cause of the issue, you have to find out the cause by reading logs of when you run /iazip and also reading CLIENT logs to see what failed to load and why.
It's the only solution, to read logs and find out what you misconfigured.
