### ISSUE TITLE
`fix-glitched-blocks` performance issue - `getBlockState`

### ISSUE THREAD

**Issue by Belceebuh** [PluginBugs/Issues-ItemsAdder#3202]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

belzzebuh

### What happened?

I generate spark profiler and itemsadder generate lag:

https://spark.lucko.me/BNLt5oS4U3

### Steps to reproduce the issue

1. use /spark profiler start --only-ticks-over 65
2. wait 5-30m
3. https://spark.lucko.me/BNLt5oS4U3

### Server version

This server is running Universe version git-UniverseSpigot-"00064c2" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 00064c2 on ver/1.20.1)

### ItemsAdder Version

ItemsAdder version 3.6.2-beta-r4

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-673

### LoneLibs Version

LoneLibs version 1.0.30

**Comment by LoneDev6** [comment]
Thank you for your detailed report!
ItemsAdder is coded with performance in mind so I'm sure this is an edge case.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/af70beef-2a34-4c2c-a42c-9906c62c715d)

Based on the report I can tell you that it's caused by the code that makes sure that no bugged blocks is found in the world.
This code exists because some external plugins or vanilla behaviour could cause some blocks to change their blockstate and look "glitched".
This is the only way for ItemsAdder to fix that.
This issue is not that serious so you could just disable these settings in your config.yml of ItemsAdder.
```yml
  fix-glitched-blocks:
    enabled: false
```

This lag issue could be caused by another option which is not enabled by default and that you might have enabled.
Please disable it.
```yml
  convert-vanilla-blocks:
    enabled: false
```


Let me know!
In the next update I'll try to optimized this code even more but I doubt it's possible as I'm using the internal Minecraft code, so this is more likely a Mojang issue.

**Comment by LoneDev6** [comment]
I can't optimize it more than this.
As I said previously: this uses the Minecraft internal code which I can't optimize.
What you can do is change the settings as I said in my previous comment, this will fix the issue on your server.

Have a nice week!
