### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by TectonicGrinch** [PluginBugs/Issues-ItemsAdder#3271]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

ViridianZe

### What happened?

i tried to run items adder both in a contained and normal environment with other plugins iazip doesnt appear to work and errors seem to be occurring in places. server appears to work without it but not with it

## Attempted to:
Run in admin mode
Change all file structuring
Different Java Versions
Different Items adder Versions
Turned off all threat protection

### Steps to reproduce the issue

Followed default wiki steps then did /iazip

### Server version

spigot- 1.20.4-R0.1

### ItemsAdder Version

3.6.3-beta-5

### ProtocolLib Version

5.2.0-snapshot-679

### LoneLibs Version

1.0.42

### FULL server log

file attached from length being too big for box

### Other files, you can drag and drop them here to upload. (optional)

[err_log.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/13799936/err_log.txt)

**Comment by LoneDev6** [comment]
About the `The filename, directory name, or volume label syntax is incorrect` error:

There is something wrong with your server.
For some reason it can't save file attributes.
It might be due to a bad Java installation, bad Windows installation, files permissions issue.

About the `java.lang.IllegalAccessError: class ia.m.ml tried to access protected field net.minecraft.server.network.ServerCommonPacketListenerImpl.c` error:

I opened a new github issue  since you should open one report per error instead.
Thanks.
