### ISSUE TITLE
netherite amor skin

### ISSUE THREAD

**Issue by SrMonsterYT** [PluginBugs/Issues-ItemsAdder#3328]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

mauriciooficial

### Describe the solution you'd like

if it's possible to skin netherite and diamond armor, can't itemadder look at the lore of the armor, and we add 1 code in the lore like any words just for it to detect that the armor is itemadder's and has a skin?

### Is your feature request related to a problem?

how to add skin to netherite armor

### Describe alternatives you've considered

use the lore of the armor to identify the skin or some way that allows us to modify netherite armors and add skin to them

**Comment by LoneDev6** [comment]
No because it's a limitation of the game, this is the exact reason why I implemented custom armors using the leather armor trick.
There is no other way to implement that currently, it's a limitation of Minecraft and I don't work for Mojang so I cannot edit the client code, sadly.
All other plugins have this limitation for the same exact reason.

Please refer to the easy tutorial to create custom armors: https://itemsadder.devs.beer/plugin-usage/adding-content/armors
You can customize the armors stats to make it similar to netherite if this is your goal.

Have a nice week.
