### ISSUE TITLE
IA 4.0

### ISSUE THREAD

**Issue by PortableGames** [PluginBugs/Issues-ItemsAdder#3337]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

I think it's time for LoneDev to stop supporting several years old versions of mc and focus the plugin on the new versions 1.20.4+ . While it's commendable to maintain those old versions , but why on earth?  Why maintain such a perfect plugin even for versions that don't support modern features like blockentity or new resourcepack features.. maintaining support for those versions costs too much time and constant bug fixing. It would be enough to catch the new wave and be modern..

### Is your feature request related to a problem?

Forget about several years old versions of mc 

### Describe alternatives you've considered

Start developing for modern minecraft

**Comment by LoneDev6** [comment]
I'd love to stop supporting old versions as it takes me so much time updating the compatibility.
I have 1 implementation of ItemsAdder for each version of the game and in some cases some parts are also reimplemented per-client.
This takes me a lot of time to maintain, test and make sure everything is optimized and stable for every version.

I sadly cannot get rid of recent old versions, because people are still running old server versions.
https://pstats.devs.beer/plugin/bukkit/ItemsAdder/6

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/beee57f8-0d87-4ad4-824e-96bc18bc12ac)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/2ef2e359-1b23-41dc-b835-dab3e3812603)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/32299d25-d275-4a30-b59c-e4e1ecaa9f69)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/b33902af-480e-4fe8-b007-91ed2f741cc9)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/128537ab-aa14-4d94-9093-d84046872baa)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/128eede4-9ccb-4ad4-b632-2f0fe9710b88)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/e454f573-b3f1-49eb-bf36-3603ff631258)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/f1815cf1-4d0d-4ccd-9e34-b800afcadbd1)

The compatibility I can get rid of is only 1.17.1, but has no sense to get rid of a mid version as 1.16.5 is still widely used.
You might think "300 servers are not a lot". But imagine 300 customers contacting me about the fact that I have removed compatibility for their server.
300 bad reviews are not a risk I want to take for now.

1.19.4+ features are already planned and will be added in the next updates, right now ItemsAdder recent updates are focused on stability, performance optimization and restructuring of bad designed features.
I will work on some of the promising features right after ItemsAdder latest beta updates start to feel stable enough.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2458
https://github.com/PluginBugs/Issues-ItemsAdder/issues/3193
https://github.com/PluginBugs/Issues-ItemsAdder/issues/3082
