### ISSUE TITLE
iaentity custom npcs and emotes become invisible

### ISSUE THREAD

**Issue by TerryLVM** [PluginBugs/Issues-ItemsAdder#3350]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

terrylvm

### What happened?

iaentity custom npcs (using citizens) and emotes become invisible when I leave the chunk. It started happening in versions after ItemsAdder_3.6.1-beta

### Steps to reproduce the issue

1. get away from the npc a little
2. they become invisible
*They are still working but invisible, it happens the same with emotes 
*This issue is in the new versions of itemsadder, as I tested, the bug is not present in the ItemsAdder_3.6.1-beta version but it is present in the versions after this.
*Im not sure if it also happens on world changing

### Server version

git-SlimeWorldManager-25 (MC: 1.20.4)* (its basically paper 1.20.4 )

### ItemsAdder Version

version 3.6.3-beta-8

### ProtocolLib Version

5.2.0-SNAPSHOT-679 

### LoneLibs Version

1.0.45

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13972629/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/uQXqFbtbKSI

**Comment by LoneDev6** [comment]
I cannot reproduce the issue, we need to find how to trigger this issue as the provided steps are not triggering it on a clean server.
Please make a video of the issue.

https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/e04170cc-b615-444a-956b-59440ec4357c

**Comment by TerryLVM** [comment]
Maybe is not leaving the chunk, it happens when the entity is no longer visible

**Comment by LoneDev6** [comment]
I enabled the chunks debug to see that I'm leaving the chunk as advised.
Do you have a clear way to reproduce the issue? Maybe you can make a video.
Thanks

**Comment by TerryLVM** [comment]
I attached a video
https://youtu.be/uQXqFbtbKSI

**Comment by LoneDev6** [comment]
Can you try to update:
- LoneLibs
- [ProtocolLib](https://ci.dmulloy2.net/job/ProtocolLib/)
- [Citizens](https://ci.citizensnpcs.co/job/Citizens2/)
- ItemsAdder
all to the very latest version?

**Comment by TerryLVM** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/assets/152677930/dc695424-ca30-4c10-85d4-aa5550926756

**Comment by Asherate** [comment]
Hi, i got the same things on my server with all plugins updated

**Comment by LoneDev6** [comment]
I cannot reproduce the issue.
There am I doing something different?

Here are the models used:

https://builtbybit.com/resources/technoblade-pet.24367/
https://builtbybit.com/resources/npc-3d-for-model-engine-mmmobs.26632/

Here is a video:

https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/1e025bc5-439d-4435-8e3e-4e62e127acaf

**Comment by TerryLVM** [comment]
I regenerated the itemsadder folder and added only the textures you passed. I repeat, the itemsadder config has nothing new. This is what happened (same thing)

Note that in ItemsAdder 3.6.1-beta this works fine, so something you changed after that version is causing this.

https://github.com/PluginBugs/Issues-ItemsAdder/assets/152677930/f8330ce0-a445-4d52-9d0d-e0432cdd3160

**Comment by LoneDev6** [comment]
Is it possible for you to open a private thread on my forum and send a link to download a very simple server where you can trigger the issue? use the "payment issue" category so that it's a private ticket. https://forum.devs.beer/
So that I can host it directly and debug the issue?
As I can't in any way reproduce the issue as you can see in my video.
Thank yoy.

**Comment by alantr7** [comment]
I'm having the same issue.

Models reappear if I use /npc despawn and /npc spawn commands. Also, models reappear if I do CustomEntity#respawn(Player). I assume ItemsAdder is not sending entity packets for custom models.

When I enter the chunk again, I can quickly see the zombie entity showing up, and despawning (because that's the base mob used), but the model never loads. So, NPC is there for sure, CustomEntity is there for sure, it's just not being sent to players.

I know the CustomEntity is there because I used: (for invisible models)
```java
var entity = CustomEntity.byAlreadySpawned(npc.getEntity());
if (entity != null) {
    Bukkit.getOnlinePlayers().forEach(entity::respawn);
}
```

ItemsAdder 3.6.3-beta-13
Citizens 2.0.33-b3327
ProtocolLib v5.2.0-SNAPSHOT-679

**Comment by alantr7** [comment]
Also, I attempted to do CustomEntity#respawn on ChunkLoadEvent and it would not work. Same with NPCSpawnEvent with CHUNK_LOAD spawn reason. I think it has something to do with player proximity rather than chunks.

**Comment by LoneDev6** [comment]
I will do more tests, Citizens is such a mess to handle due to how its custom NPCs properties work internally.
Anyway as you can see in my video I couldn't trigger it so I really need a simple test server setup so that I can run it on my machine and see the issue, because in my setup I cannot.

**Comment by NoHere32** [comment]
Hey ! I would like to bring more information to the table. To make the "bug" happen you need to do:
Have between 4 and 5 iatentities NPCs
To easily to the bug, you need to move away from the iaentities npcs and return quickly to the iaentities npcs and it will be glitched

then the bug will work by magic

https://youtu.be/LzlLMMh8vG8

**Comment by LoneDev6** [comment]
Will be tested again but last time I couldn't reproduce the issue.
Check my previous video: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3350#issuecomment-1924183670

**Comment by NoHere32** [comment]
> Will be tested again but last time I couldn't reproduce the issue. Check my previous video: [#3350 (comment)](https://github.com/PluginBugs/Issues-ItemsAdder/issues/3350#issuecomment-1924183670)

Your trial is clearly in an empty mode with nothing else to load around it. There are no bugs in 1.20.1, at least as far as I'm concerned.

**Comment by ChristianHoefer** [comment]
Same Issue here but i can reproduce it on citizens npc's also as on per code spawned entities

Server: 1.20.4
Citizens: 2.0.33
ItemsAdder: 3.6.3-release 3
ProtocolLib: 5.2.0-SNAPSHOT-679
LoneLibs: 1.0.54

**Comment by ChristianHoefer** [comment]
Now i have created a docker instance with only the four plugins above metioned by me. The problem persists. I can send you the Docker archive if you need it.

**Comment by ChristianHoefer** [comment]
Okay after testing a little bit, i think i have found the issue. 

The Problem are on the client side. Testing with two accounts, one see all entity and one not. 

More clear and reproducable: if the entities are loaded within users field of view there is all fine. But if the entities are loaded outside of the users field of view, the problem occurs. I think the client doesn't render the skin of the custom entity, thats because the base entity are present but hidden. 

The problem occurs on citizen npc's with custom skin but also on iaentity spawned entities (not a npc)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/6047702/bdc3aed7-eade-478b-8a00-fb4af8cb3eeb

**Comment by ChristianHoefer** [comment]
Any News on this?

**Comment by LoneDev6** [comment]
Probably related to this? #3818
