### ISSUE TITLE
How can I change the sword to items bigger in Itemsadder? (item scale)

### ISSUE THREAD

**Issue by gclogs** [PluginBugs/Issues-ItemsAdder#3391]
### Terms

- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.
- [X] I'm using the very latest version of ItemsAdder and its dependencies.

### Discord tag (optional)

gosmos_

### Describe the solution you'd like

```json
{
    "parent": "namespace:item/handheld",
    "textures": {
        "layer0": "~~"
    },
    "display": {
        "thirdperson_righthand": {
            "rotation": [-45, -90, 0],
            "translation": [0, 7, 1.5],
            "scale": [1.25, 1.25, 1.25]
        },
        "firstperson_righthand": {
            "rotation": [-30, -90, 0],
            "scale": [1, 1, 1]
        },
        "thirdperson_lefthand": {
            "rotation": [70, 0, -180],
            "translation": [-5, -6.5, 9],
            "scale": [1.5, 1.5, 1.5]
        },
        "firstperson_lefthand": {
            "scale": [0, 0, 0]
        }
    }
}
```
This works in vanilla, but not in the JSON of the Itemsadder.
I wanted to scale it up to represent a greatsword.

### Is your feature request related to a problem?

Yes

### Describe alternatives you've considered

I looked and there is no json file associated with item scale.
The only way I could find was to scale via blockbench.
I don't know how to use blockbenches flexibly.. 
So i don't know what should i do

**Comment by LoneDev6** [comment]
You just have to use a custom json model for your sword instead of a direct png texture.
Exactly how I do that for some special items, check an example here: 
YML file [here].(https://github.com/ItemsAdder/OtherPacks/blob/816f9189d3e83d7e2bebfd3a3d98484b19a4d834/contents/iaspecial_swords/configs/items/floating_sword.yml#L11)
Model file [here](https://github.com/ItemsAdder/OtherPacks/blob/816f9189d3e83d7e2bebfd3a3d98484b19a4d834/contents/iaspecial_swords/resourcepack/iaspecial_swords/models/item/floating_sword.json).


Make sure to use the correct paths and namespaces when creating your own model (this requires basic knowledge on how resourcepacks are work and are organized, as stated in the [TOS](https://itemsadder.devs.beer/other/tos)).

Note: this is not a place to ask for help configuring files but a place to report bugs.
To ask for help use Discord or the forum, thanks.

**Comment by gclogs** [comment]
No one at Discord answered my questions... :(
Tysm! Have a good one :)
