### ISSUE TITLE
Chat messages broken when ItemsAdder is installed

### ISSUE THREAD

**Issue by Llopeando** [PluginBugs/Issues-ItemsAdder#3397]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Hi there!
In our server we are using ItemsAdder and VentureChat, and after installing ItemsAdder (configuring self host and all of that), the chat just broke down, as you can see in the image at the bottom of the report.

### Steps to reproduce the issue

1. Install VentureChat
2. Install ItemsAdder
3. The chat messages will broke down. (/msg commands and so on will work perfectly fine)

### Server version

This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-11

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### FULL server log

Full server log: https://mcpaste.io/a143d5c336d29dc2

### Screenshots/Videos (you can drag and drop files or paste links)

![imagen](https://github.com/PluginBugs/Issues-ItemsAdder/assets/21044193/2f71b9f6-41ce-48a3-9985-678ccb380243)

**Comment by Llopeando** [comment]
It seems to be the "font_images" and "text-effects" settings for the chat, which if they are enabled, they will break the chat.
I will leave the issue open, if you think that this is an actual bug or not.

**Comment by LoneDev6** [comment]
I think it's an issue of VentureChat to be honest, as EssentialsX chat and similar works fine

**Comment by GsTio86** [comment]
I also encountered the same problem, but after I turned off font_images and text-effects, everything worked fine

**Comment by LoneDev6** [comment]
Chat code is currently overcomplicated and very hard to maintain due to the fact that I want to have both Spigot and Paper compatibility.
In a future update I will drop Spigot compatibility for font images and font effects in chat due to the fact that no one is using Spigot.
Professional servers are using Paper due to its extensibility, feature rich API and performance improvements.
This will allow me to easily fix this kind of issues, hopefully.

Sources:
https://bstats.org/global/bukkit
![Image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/c57debaa-ec58-4f68-88f2-bf90cc3d39cf)

**Comment by madebygood** [comment]
Please solve it
