### ISSUE TITLE
performance msptspikes

### ISSUE THREAD

**Issue by matipoirierg** [PluginBugs/Issues-ItemsAdder#3675]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

supersintiendo64

### What happened?

Parsing some intensive stuff to essentials
https://spark.lucko.me/FiTOUEoecZ

### Steps to reproduce the issue

From the timings, teleporting.

### Server version

This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)
You are running the latest version

### ItemsAdder Version

3.6.4-2

### ProtocolLib Version

689

### LoneLibs Version

1.0.54

### Full server log

https://mclo.gs/AGnXZd1

**Comment by LoneDev6** [comment]
Timings reports must be generated during gameplay not at server start or during plugins loading/reloading.

This has nothing to do with ItemsAdder since the only part in the timings report related to ItemsAdder is the initialization part which is called only one time at the server start.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/82b21322-1380-4dbd-bb56-36aa1a041e09)


The high usage you see is related to Essentials only.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/1c48b685-3519-4bf9-8ccc-b06467a84155)
