### ISSUE TITLE
Warn if ViaVersion is installed and user joins with different game version than the server

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3683]
Warn if ViaVersion is installed and user joins with different game version than the server.

## Why?

ViaVersion is a cancer if used incorrectly. The purpose of ViaVersion was to be able to allow clients to connect to a multi-version lobby where players can decide which server they want to join.

Each server has its own version, for example, survival is 1.20.5 and PVP is 1.8. This allows people to connect to the same lobby server which is the main hub of the server community.

Server admins abuse this power to allow players to play on survival servers by joining via 1.8, 1.9, 1.13, 1.18, 1.20 on 1.20.x servers. This causes multiple incompatibilities, instabilities, bugs, glitches to happen.
The reason for this to happen is because clients (and servers) had A TON of changes between their versions, most of them are crucial.

Expecting a flawless gameplay is impossible because of how many changes were introduced between versions.

A clear example of a successful server which allows only one version to join is [OriginRealms](https://originrealms.com/) which is one of the most customized Minecraft multiplayer survival experience, no one can tell the opposite.

I don't see any reason to continue this nonsense of expecting gameplay to be stable while allowing ancient versions of the game to join your server, or worse, keep an old version of the server and allow new client versions to join.

ItemsAdder has tons of hacks coded to check client version and server version and then enable some special fixes to avoid crashes/glitches (let's say) on 1.18 clients joining 1.20 servers. I want to stop having to maintain this kind of tricks which are unstable and introduce nothing but stress to both me and the customer.

So please, consider to stop allowing multiple versions to join your survival/gamemode server.

**Comment by Andre601** [comment]
A few corrections for the sake of clarity:

- ViaVersion is for newer clients to join old servers (i.e. 1.9+ on a 1.8 server). ViaBackwards is used for the oposite (Newer server versions allowing older clients)
- Origin Realms allows multiple versions, tho it is from what I know limited to one major version range. This means that right now any 1.20+ client *should* be able to join (I know for a fact the server isn't 1.20.4, but I can join with 1.20.4)

**Comment by LoneDev6** [comment]
I don't want new clients to join old server too since Mojang does some changes which messes up with stuff.
For example 1.20.2 clients joining 1.20.1 servers will have issues seeing some entities due to the ride offset being different, in my case CosmeticsCore had issues I had to deal with with some per-version implementations (checking both server and client).

**Comment by dinobossytnew** [comment]
I think it's perfect and reasonable. As you correctly say, ViaVersion is not for creating multi-version modalities but for the lobbies that everyone joins after passing through the proxy to the lobby and choosing their modality according to the different versions of each modality. It is true, and very much so, that I used to do what you say: I used ViaVersion incorrectly until after learning and learning more, I understood that everything has a limit.

**Comment by PSYCHEER** [comment]
> A few corrections for the sake of clarity:
> 
> * ViaVersion is for newer clients to join old servers (i.e. 1.9+ on a 1.8 server). ViaBackwards is used for the oposite (Newer server versions allowing older clients), so ViaBackwards is to blame here.
> * Origin Realms allows multiple versions, tho it is from what I know limited to one major version range. This means that right now any 1.20+ client _should_ be able to join (I know for a fact the server isn't 1.20.4, but I can join with 1.20.4).

A bit of additions to the corrections:
* Using multiple RPs on one server was possible in older versions too, you just need to have a good tool which checks version of player and sends RP for his version. Between 1.20.2 and 1.20.3 was some changes in ResourcePacks which fucked some things for older clients. Same in 1.20.4 and 1.20.5...
* 
* ViaVersion or ViaBackwards, client should join on the version on which server is on. Nothing else. Because it doesn't matter if newer is on older or older is on newer, still can break a lot of things or do flaw things and exploits

**Comment by fra130701** [comment]
Dropped itemsadder for this reason
If my server has 1000 online i must offer support for newer versions

If i have a gamemode on 1.20.4 i can't update that to 1.21.1 only because itemsadder dev hates viaversion

**Comment by PSYCHEER** [comment]
> Dropped itemsadder for this reason If my server has 1000 online i must offer support for newer versions
> 
> If i have a gamemode on 1.20.4 i can't update that to 1.21.1 only because itemsadder dev hates viaversion

Nobody from us hates Via* in form it should be used to. The way that community uses the Via* is what causes bad things to happen and that’s what we hate.

It’s like “Microsoft drops support for Windows 7 with new W10” and they will community say “I’m not updating nor using win as I need win7 only”

**Comment by fra130701** [comment]
"via version is a cancer"

Minecraft is not windows
Hypixel too allows multiple versions on 1.8.8 modes

**Comment by Andre601** [comment]
> "via version is a cancer"
> 
> Minecraft is not windows Hypixel too allows multiple versions on 1.8.8 modes

And? Hypixel isn't a go-to example of a good Server. Mainly because you can't - and shouldn't - use it to compare with things such as plugins as chances are high that they do not just use some random spigot plugins on their servers.

Also, just like ViaVersion IS cancer, IF used wrong, is 1.8 itself cancer too. Hypixel is doing nothing more than keeping the dead alive for no reason other than supporting the vocal minority that complains about the 1.9+ PvP.

Either way, this is not a discussion for this issue AT ALL. Please keep it away from here or I'm forced to lock it.
It's a fact that ViaVersion is not meant to be used for a full-on Server but rather a multi-version lobby. It's features and conversions aren't perfect and will mess things up. If you choose using it for things it's not really designed for, you're on your own, as why should people like us waste time trying to fix issues other plugins cause?

IA is designed to support a specific set of versions. Any other version not in that range is not considered supported nor something we will fix, as how can we fix something that isn't supported (yet)?

Either way, I stated my points on this matter here and repeat again: If you continue this useless talk, the issue will be locked.

**Comment by fra130701** [comment]
I'm only on a 1.20.4 server and i want to support texture loading for 1.21.2 and 1.21.3 users
I'm not allowing backwards compatibility, infact i have only viaversion

I'll kepp this issue away from this thread
But keep in mind that this is a bad think for servers owners using itemsadder, because we need to allow new versions even with itemsadder
I'm forced to switch from itemsadder to another solution from using ia from maybe 2 yearsh

**Comment by PSYCHEER** [comment]
As I've mentioned a bunch times, that's not IA incompatibility neither the RP itself as mojang provides in changelogs, they did changes in RP, that's the reason why it's incompatible at the moment.
Potential fix will be worked on (if even possible) with new version of stable paper server core.

These are our last statements @Andre601 lock it

Best regards.

**Comment by noaskers** [comment]
Why just don't support the server version?

So if the server version is 1.21 support all .1, .2, .3 versions.

**Comment by kylemarham** [comment]
Paper already has builds out for 1.21.3. These builds will not be changing drastically. Just do the work.

**Comment by LoneDev6** [comment]
ViaVersion works with ItemsAdder, never said I dropped support.
What I said is that I cannot guarantee it to work without some glitches, as ViaVersion itself is not a stable solution.
I use ViaVersion to make tests with various clients, for example 1.20.6 server and 1.21.1 client.
