### ISSUE TITLE
Itemsadder stops the server from closing/restarting

### ISSUE THREAD

**Issue by bruhhhwarrior** [PluginBugs/Issues-ItemsAdder#3836]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Itemsadder has some issues with ViaVersion that causes the server to not close and be stuck on closing. I looked it up in the viaversion github and i saw this : https://github.com/ViaVersion/ViaVersion/issues/3972#issuecomment-2231478060

I know you are not a huge fan of viaversion but this happens in the latest V3 version too and its been happening for some time, so i hope you may consider looking into this!
The issue i linked should have sufficient logs that you can use and i also added my own

### Steps to reproduce the issue

Have IA V3 and viaversion installed at the same time and close the server

### Server version

Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)

### ItemsAdder Version

V3.6.4-Release-3

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.55

### Full server log

[In the ](https://mclo.gs/27wpnLu)

### Error (optional)

```shell
[21:05:25] [Server thread/INFO]: [ViaVersion] Disabling ViaVersion v5.0.1
[21:05:25] [Server thread/INFO]: [ViaVersion] ViaVersion is disabling, if this is a reload and you experience issues consider rebooting.
```

**Comment by Andre601** [comment]
Nothing in your logs hints at ItemsAdder being the issue here. In fact, ItemsAdder disables way before ViaVersion, which prints the warning you provided.
Also, the error at the very end is by the Tebex plugin, not ItemsAdder.

Due to the above will I close this issue now. If you have actual proof of this being an ItemsAdder, issue, provide it and I may re-open the issue, tho I suggest you test this issue with just ItemsAdder and its dependencies alone and then slowly add the plugins back to see what may be the actual cause.
