### ISSUE TITLE
possible solution for head glitch when emotes are on

### ISSUE THREAD

**Issue by bruhhhwarrior** [PluginBugs/Issues-ItemsAdder#3852]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Hello lonedev

I love the emotes in itemsadder but the placed head texture bug has always been a bit of a downside to it,
Recently i discovered this other plugin that seems to have an alternative that does not bug out placed heads!

[Here](https://francobm.gitbook.io/magicgestures/new-rendering-system) is their wiki page on how they achieve it.
and [here](https://francobm.gitbook.io/magicgestures/old/old-system/limitations) is their old method that (i believe) functions alot like the one itemsadder uses right now.

I understand this may not be a priority for you, and i understand that, but i just saw this and felt like i had to let you at least know!

### Is your feature request related to a problem?

yes

### Describe alternatives you've considered

the other plugin i linked but like id prefer using itemsadder

### Additional context

if this is something you'd consider, would you consider doing it for v3 too? anyways,
Thank you for developing such a great plugin!

**Comment by Andre601** [comment]
> And what is the skin API limit for uploading skins to the server? Won't it be somehow limiting if you try to upload hundreds of skins a day?

Well, the plugin OP linked uses https://mineskin.org
That site offers generating official skin files by uploading them to mojang using hundrets (223 in fact) of accounts donated by people, distributing the amount of skins uploaded onto individual accounts, because each account has their own rate limit.

Like instead of a single account uploading 100's of skin files to the Mojang Servers is it hundreds of accounts uploading individual files, reducing the delays significantly.

**Comment by Andre601** [comment]
I don't think it wouldn't be that much of an impact. IA wouldn't need to request generation of every player that joins, but those who would want to emote.
Also, Mineskin remembers and recognizes the same skin files and returns whatever it has already retrieved before here from what I know.

Tho, personally am I not in favour of such an idea myself. While this would indeed be a neat solution for a core shader-less aproach are there still downsides such as:

- Delays due to textures first needing to be generated by Mineskin for use
- The above issue every time the player changed their skin
- Requirement to implement a system to convert a skin texture of a player into multiple skin texture files, one for each body part.
