### ISSUE TITLE
Add interact event for item display furniture

### ISSUE THREAD

**Issue by WMGameLive** [PluginBugs/Issues-ItemsAdder#3901]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

wmgamelive

### Describe the solution you'd like

Just like armor stand and item frame, there is placed_itemframe.interact and placed_armorstand.interact event for they, but the new item display don't have any events. so I want a new event maybe like placed_itemdisplay.interact.

### Is your feature request related to a problem?

I have a lot of furnitures are using interact event, but if I convert they to item display, I can't do that anymore.

### Describe alternatives you've considered

.

**Comment by LoneDev6** [comment]
You have `placed_furniture.interact` and `placed_furniture.break`.
Use them instead, the `placed_armorstand` and `placed_itemframe` events are legacy and still there only to keep compatibility with old packs.

**Comment by WMGameLive** [comment]
> You have `placed_furniture.interact` and `placed_furniture.break`. Use them instead, the `placed_armorstand` and `placed_itemframe` events are legacy and still there only to keep compatibility with old packs.

Sorry, those two events are not listed on the wiki, so I didn't know they existed. Thank you.

**Comment by WMGameLive** [comment]
placed_furniture still not work for Item Display.

**Comment by LoneDev6** [comment]
Seems the game itself doesn't send any interaction packet when interacting with item display.
What you can do it make the entity have a solid hitbox, so that the event is triggered when the player interacts the barrier block.
In the meantime I will implement a workaround, but it won't work always.
I will catch when the player interacts with blocks, then check if the entity is in the line, but it won't work if player interacts with AIR (looking up for example).
Better than nothing.

I'd avoid using interaction entities as they don't have multi-dimensional hitbox, so it can only be increased on 2 axis (height, width).
