### ISSUE TITLE
I can't see textures

### ISSUE THREAD

**Issue by eky81** [PluginBugs/Issues-ItemsAdder#3929]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

eky.81

### What happened?

I can't see armors and weapons textures. I buy elitecreatues pack, i drag and drop but didn't work.
![Screenshot_1](https://github.com/user-attachments/assets/dfc59dcc-ec8e-45bd-b4f9-14feacfcb272)

### Steps to reproduce the issue

![Screenshot_1](https://github.com/user-attachments/assets/86f90b94-9a16-4c63-9230-61f4c1c2e2f7)

### Server version

This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)
You are running the latest version

### ItemsAdder Version

3.6.4-release-3

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.56

### Full Server Log

https://mclo.gs/7FRrkYt

**Comment by SrMonsterYT** [comment]
request support at elitecreatues

**Comment by Andre601** [comment]
Your issue is a bad configuration of elitecreatures and not ItemsAdder, as you can see in Line 5000+ in your provided log files. This is not an issue we can or will fix here.

Also, you have a lot of other issues here that you should fix. Namely:

- ItemsAdder is unable to get a hash from the RP through self-host. This is usually caused by either a firewall blocking the connection, a service like Cloudflare blocking the connection if the IP/Domain used is proxied, or a badly set port
- ItemsAdder reports a lot of duplicate entries. This is usually the cause of a bad contents folder. Best aproach would be to clear the ItemsAdder folder (make a backup of it first) and let ItemsAdder recreate it. Then slowly add back the different addons to see if one causes these problems.
