### ISSUE TITLE
@PortableGames Dude, you spill a lot of nonsense here for nothing of substance...

### ISSUE THREAD

**Issue by PortableGames** [PluginBugs/Issues-ItemsAdder#3960]
@PortableGames Dude, you spill a lot of nonsense here for nothing of substance...

> Lonedev is trapped. The plugin is not ready for new versions and before everything is fixed there will be a new version. He's starting to miss the train. He should open the plugin as opensource and get help from loyal fans. But he thinks he can do it all by himself.

Currently, the latest version Mojang works on is 1.21.2, which by the looks of it changes nothing of substrance outside adding experimental tests for the community to play around with. It will most likely be the same as 1.21.1, as in making it compatible with 1.21 in general and may even be less of a hassle than 1.21.1 was itself.
If there are changes, they most likely will be small in nature and fast to adabt to. I myself provide LoneDev with updates on recent Snapshots, so he's aware of what is to come here.

And right now is IA - from what I understand - working on 1.21.1 itself. What you count as "working" is up to everyone's own interpretation, but I myself consider IA enabling and loading a RP as functional.

Also, your view of Open source is very flawed. Making a plugin OS does not result in it automatically getting a ton of contributors in the end.
Just look at [Nova](https://github.com/xenondevs/Nova): Open source and quite popular amongst people, yet like [99% of the commits are by the same core people](https://github.com/xenondevs/Nova/commits/main/) - mainly NichtStudioCode - and not from various outside contributions.

If anything, making ItemsAdder open source could even become counter productive. As of right now can LoneDev code the plugin his way in his coding style. With open sourcing it would there be a ton of extra work he had to deal with:

- Keep track of features other people want to implement.
- Ensure his code style is followed.
- Make proper tests of all the PRs to ensure there is no impact on performance or functionality.
- Constantly update his local copy with latest merged changes to keep it updated and not have merge conflicts.
- ...the list goes on.

And keep in mind that I say this as someone who is for open source projects and tries to make all my own projects open source here.

> Modern Minecraft is no longer spigot/paper but fabric or quilt. Most projects are opensource and the community participates in rapid updates to new versions.

Then go and use Fabric or Quilt (Also, there is NeoForge now, which also seems to gain popularity)?
Like, why mention this even?
And refer to my previous paragraph on why you have a dillusional view on open source. The ones you think gain lots of participants are often times the most popular ones, but that doesn't reflect the majority of every OS project out there, nor the complexity that is behind maintaining such a project.

> The idea of maintaining support for old versions is complete bullshit. Most people want the new features of the new version anyway. Why maintain compatibility for 4 year old versions? . Isn't it better to focus on always supporting the latest version? It would also be good advertising: we always support the latest version of mc.

You must've missed the last 2 months dude... LoneDev does not try to keep backwards compat for 4+ years old versions. Quite the oposite actually.
v4 is actually **dropping any support for versions before 1.20.5**, making its supported versions 1.20.5, 1.20.6, 1.21 and 1.21.1.
Given that you should stay with the latest patch versions for max security and bugfixes can we say v4 supports 1.20.6 and 1.21.1. 2 out of the countless versions before those that v4 supports.
And he at one occassion even mentioned that v3 won't receive updates anymore (maybe some smaller bugfixes), as nobody should stay on older versions. He knows this just as well as you do.

> Lonedev should think twice and instead of wasting time fixing old bugs in old versions he should step into real support for 1.21.1 and future 1.21.2 (btw many fabric mods already support 1.21.2 snapshots)

The main issue with new version support is the api a software relies on. Mods support 1.21.2 snapshots because Fabric, Quilt, NeoForge and Forge already have a mod loader and API version for it.
Spigot and Paper do not make versions of their API and server for snapshots as A) it takes time and B) is effectively wasted once the next snapshot or full version rolls around. And nobody really runs a snapshot version on their production server (unless it's something like an april fools snapshot maybe).
If ItemsAdder was a standalone thing, then perhaps asking for support of the snapshots would be okay. But the plugin is still a plugin and depends on the server it runs on, just like mods depend on the modloader they run on. You can't claim he should work on support for a version that has no active API support yet by the servers it needs to function.

You clearly have no idea of how the plugin world works here, especially in the open source section here, so with all due respect, please stop spreading nonsense in these places here, as it is not productive on any level, nor does it help LoneDev in improving the plugin. All it does is showing you as a complaining, entitled individual who thinks plugin development is the same as modding, which they are clearly not.

And to avoid this issue being further derailed will I lock it. Sorry, not sorry.

> [!NOTE]
> All the info stated above is *my* opinion on the matter. I do not speak on LoneDev's behalf here, nor do I have his agreement on anything said here. Do not assume what I said here is what he thinks too, as it may or may not be different.

_Originally posted by @Andre601 in https://github.com/PluginBugs/Issues-ItemsAdder/issues/3958#issuecomment-2323038961_

**Comment by Andre601** [comment]
This entire thing is not really meant for this issue tracker, nor ItemsAdder itself, so I ask you to please stop it here and now, as it really doesn't help anyone here at all.

But to answer your argument, which honestly answers barely anything:
Mods are not a justifiable comparison to plugins. Those two are completely separate ecosystems with completely different aproachers on doing things.

Mods can "do this better", because unlike plugins do they have less restrictions. A mod has direct and unrestricted access to the Minecraft source code and can inject, modify or even remove code at their own discretion using whatever methods the modloader provides (Mixins for Fabric/Quilt and whatever else Fore and NeoForge use here).
Plugins do not have this luxury available. They are meant to rely on and use a provided API from the server, that is rigit and limited. And while they too can access internal code of the server (The so called NMS code) is this limited and does not allow the injection or modification of it... At least not without an extreme hacky aproach and without risking other plugins breaking, if they rely on this particular piece of code.

This is also why hybrid servers such as Mohist, which try to merge these two ecosystems together, are hated amongst the plugin-dev community and not at all recommended by any sane person, as they try to merge two APIs who aren't meant to be merged, causing various plugins to break and not work anymore in the end.

So, saying there are these open source mods that work and "do it better" is an unfair comparison as it is literally equal to comparing an apple to a banana and saying one is better than the other... It doesn't work as it is a comparison of two different things that aren't part of the same ecosystem/group.

Also, if you really think these mods are better, then go and use them. Nobody here would care if you stop using ItemsAdder, as it wouldn't make a difference to the status quo.
Just stop bringing up mods as an attempt of shitting on ItemsAdder for not being as good here, as it's simply a unfair thing and not justified.
