### ISSUE TITLE
[Suggestion] Set Armor Bonus Effects!

### ISSUE THREAD

**Issue by ArgonGaming** [PluginBugs/Issues-ItemsAdder#400]
**Is your feature request related to a problem? Please describe.**
The feature request is not related to a problem, but rather a suggestion to a very cool gameplay mechanic that many other plugins and servers have offered up, except without the unique concept of custom armor.

**Describe the feature you'd like**
With custom armor sets, and your fabulous API, I believe adding a set bonus effect feature shouldn't sound too far-fetched, and would make for much more unique gameplay. As long as it identifies the set (configurable in a config yml), it'd be awesome to have something like this. 

This is NOT an effect applied when only one piece of armor is worn, which we already have. This would have an identifier that checks if the player is wearing the ENTIRE set of armor, THEN applying the effect. 

By effect in this context I do mean vanilla potion effects, but it would be nice to add in NBT Attributes as an option as well, such as: Extra Hearts, Extra Armor, Luck statistic, etc..

**Comment by imparium-de** [comment]
I second this idea! We're currently looking for exactly this mechanic, where e.g. the Aqua Aura armor gets an Aqua Affinity V effect when the whole set is worn. Same thing with something like fire resistance or blast protection, where it makes more sense when applied to a kit instead of a single item. :)
