### ISSUE TITLE
Texturepack dosnt work on 1.21.1

### ISSUE THREAD

**Issue by SliderKP** [PluginBugs/Issues-ItemsAdder#4017]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

exxslider

### What happened?

Texturepack dosnt work on 1.21.1 if i join with 1.20.4 i can see textures.

### Steps to reproduce the issue

install texturepack and join to server.

### Server version

Pufferfish 1.21.1 build #15

### ItemsAdder Version

4.0.2-beta-release-11

### ProtocolLib Version

#726

### LoneLibs Version

LoneLibs 1.0.59

### Full Server Log

https://mclo.gs/8AG1VEU

MINECRAFT CLIENT LOGS ERRORS:
https://mclo.gs/PHbYPbB

**Comment by PSYCHEER** [comment]
I just looked into your client log.
Many of issues of missing textures for models, missing sprites etc
How RPs changed in last versions is possible it wont load because of that and because of shaders version mismatch

## How to fix shaders?
Search trough your `contents` folder for `shaders` which should be under core folder.
Back it up and remove from contents folder.
Do `/iazip` and pray that was the only issue

# DON'T FORGET TO FIX YOUR MODELS AND TEXTURES IN CLIENT LOG!
