### ISSUE TITLE
No walking sound on stone blocks (but works on grass blocks)

### ISSUE THREAD

**Issue by svaningelgem** [PluginBugs/Issues-ItemsAdder#4093]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

bumbabot

### What happened?

Walking around on sandstone is not audible for other players.

In my own plugin I capture these sounds with PacketEvents to selectively adjust them to be sent or not.
That's where I noticed that I wasn't hearing any footstep sounds on sandstone blocks. But I was hearing them on grass.

What I first did was delete all plugins (ie pure vanilla server) -- footsteps audible.
Then I added ItemsAdder & removed its configuration (to ensure it wasn't a config issue) -- footsteps not audible

I'm guessing the event get cancelled somewhere in IA, because in PacketEvents I can actually see the sound event being emitted, and that it's a `[...]stone.step`. So it's there. It's just not audible. And this is with only having IA as a plugin.

### Steps to reproduce the issue

Walk on sandstone (or obsidian) blocks. Hear it **with another client**. That's the important part! Because with your own client you will always hear the steps.

### Server version

[17:18:01 INFO]: Checking version, please wait...
[17:18:01 INFO]: This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-497 (MC: 1.20.4)

### ItemsAdder Version

[16:40:24 INFO]: ItemsAdder version 4.0.3
[16:40:24 INFO]: Customized Minecraft without client mods!
[16:40:24 INFO]: Website: devs.beer
[16:40:24 INFO]: Author: LoneDev

### ProtocolLib Version

[16:40:32 INFO]: ProtocolLib version 5.3.0
[16:40:32 INFO]: Provides read/write access to the Minecraft protocol.
[16:40:32 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[16:40:27 INFO]: LoneLibs version 1.0.59
[16:40:27 INFO]: Collection of libs used by my plugins
[16:40:27 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/IOoE7ea

### Error (optional)

```shell
no error, functional error
```

### Problematic items yml configuration file (optional)

```yaml
pure default config
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/89d4647e-8ba3-48da-bc11-05fe406c223d)

**Comment by Andre601** [comment]
1. You didn't provide the actual server version and instead accidentally inserted the LoneLibs version.
2. Provide the server logs. It doesn't matter that there isn't an error. We ask for them for a reason.

**Comment by svaningelgem** [comment]
1. corrected
2. corrected

**Comment by LoneDev6** [comment]
ItemsAdder uses custom sounds with `internal` prefix to play stone and wood sounds.
I created muted sounds replacing the vanilla wood and stone blocks sounds so that the client will play no sound when it used to predict them, for example on block placing, as the sound is predicted by the client and not sent by the server.

This is useful to stop vanilla sound to be played when players walk on custom blocks that use NOTE_BLOCK or MUSHROOM as material, so that I can override the sound.

I then catch all vanilla behaviour when it should play the wood or stone sound and I play the `internal` sound, which is in fact the real sound remapped to a new name, so that the client doesn't play it automatically.

List of sounds:
![Image](https://github.com/user-attachments/assets/0eef6f03-c2b4-4f6c-aa94-c9b55f27f945)


For some reason `internal` sounds are not generated in your pack or you are cancelling the packet.
It works fine on my client, i tested it right now with 2 clients and the second client can hear the first one walking.


Check if you enabled the patch and run `/iazip`.
```yml
  custom_blocks_sounds_patch:
    enabled: true
    step:
      enabled: true
      allow_non_player: true
    other: true
```
