### ISSUE TITLE
Mushroom block problem

### ISSUE THREAD

**Issue by ffddf111** [PluginBugs/Issues-ItemsAdder#4203]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

minecraft_frog_cute

### What happened?

The mushroom surface does not change.
+ Sometimes mushrooms drop.

### Steps to reproduce the issue

1. Place a red or brown mushroom block.
2. Place another block next to the one you placed.
3. Destroy the second block you placed. (When you break a mushroom block, mushrooms will sometimes drop.)
4. Look at the surface of the first block you placed.
5. The mushroom surface does not change.

### Server version

![image](https://github.com/user-attachments/assets/f6333b1c-c631-41ab-8fa8-20cd2c10c58c)

### ItemsAdder Version

![image](https://github.com/user-attachments/assets/9f46bda5-a326-44ed-a6b5-5d3bc781137a)

### ProtocolLib Version

![image](https://github.com/user-attachments/assets/9e6ffb8d-6b0a-4d8e-9a93-70150873a0e5)

### LoneLibs Version

![image](https://github.com/user-attachments/assets/a0ba90f9-0340-4b91-b5c2-491448591ed2)

### Full Server Log

https://mclo.gs/Ayra3Do

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/user-attachments/assets/11f42d4f-e158-4f18-b1d3-eb4f055c5dc6

**Comment by Andre601** [comment]
This isn't a bug, but normal MC behaviour.
Mushroom blocks have a `77.77%` chance of dropping nothing and a `11.11%` chance of dropping 1 to 2 mushrooms (Source: [minecraft.wiki](https://minecraft.wiki/w/Mushroom_Block))

To answer the question why the block doesn't update its faces (block state) when placing blocks against it: ItemsAdder, or more accurately the different item packs you can add/make, can use `REAL` as block type, which uses the different Block states of Mushroom blocks.
So ItemsAdder disables/cancels block updates for Mushroom blocks to avoid texture glitches, or else you would see random blocks that don't make sense, as shown in this example:
![image](https://github.com/user-attachments/assets/22a30780-08db-4d9f-af56-bd628d152858)

Now, to still allow Mushroom blocks to be used is one block kept unchanged, the one you hold and use in your video).

If you're sure you don't have any item pack using Mushroom blocks (The `REAL` block type) can you disable ItemsAdder handling them in the config, by setting `disable-REAL` to `true`.
Just make sure to `/iazip` after the changes, so that the resource pack is refreshed and ItemsAdder reloaded.

> [!NOTE]
> The provided info may not 100% be accurate and is based on my own experience with ItemsAdder.
