### ISSUE TITLE
Papers in GUIS

### ISSUE THREAD

**Issue by JavituRec** [PluginBugs/Issues-ItemsAdder#4253]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

In versión 1.21.4 the GUIS have a papers

![image](https://github.com/user-attachments/assets/bd765958-fd6f-432d-8aab-008b802d0a75)

### Steps to reproduce the issue

using command /warps

### Server version

This server is running Pufferfish version 1.21.1-21-HEAD@cfa3c61 (2024-10-22T23:08:19Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 4.0.5

### ProtocolLib Version

ProtocolLib version 5.3.0

### LoneLibs Version

LoneLibs version 1.0.62

### Full Server Log

https://mclo.gs/yKMv4aW

**Comment by Andre601** [comment]
Please use ProtocolLib 5.4.0 for versions 1.21.3 and newer, [as stated in their CI page](https://ci.dmulloy2.net/job/ProtocolLib/).

Also, please test if this issue appears on a **bare-bones Server Setup** as described in https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187 to eliminate any possability of other plugins causing this problem.

**Comment by JavituRec** [comment]
My server version is 1.21.1 and the last version for Protocollib is 3.5.0

![image](https://github.com/user-attachments/assets/05577802-3cf3-4f95-a422-06d8d493005e)

in terms of bare-bones Server Setup, it has been checked and I comply with each of these aspects.

The problem persists.

Greetings.

**Comment by Andre601** [comment]
That's why I requested this to be tested on a bare-bones server setup, which wasn't done and therefore shows you (The OP) lied when filling out the issue form.

Again: Test it on a bare-bones server setup and see if the issue persists. If it doesn't is it a client version issue and/or an issue with a plugin.

**Comment by JavituRec** [comment]
> That's why I requested this to be tested on a bare-bones server setup, which wasn't done and therefore shows you (The OP) lied when filling out the issue form.
> 
> Again: Test it on a bare-bones server setup and see if the issue persists. If it doesn't is it a client version issue and/or an issue with a plugin.

If you check the shared screenshot, you will see that the client is 1.21.4 and the server is on version 1.21.1....

So the problem is the client version because if the client is using version 1.21.1, 1.21.2, 1.21.3 the described problem does not occur. It only occurs if the client has the latest version 1.21.4.

I don't know what else you want me to do but I think the problem is quite clear.

**Comment by Andre601** [comment]
Then this is a non-issue.

ItemsAdder tells you clearly both when enabling AND when a player joins with a version different than the server, to not report issues, as it can be an issue with the client version and ItemsAdder.

Here is the message in question from your own logs:
```
[13:15:29] [Server thread/INFO]: [ItemsAdder] ViaVersion detected. Do not report glitches when joining using game versions different than the server version.
[13:15:29] [Server thread/INFO]: [ItemsAdder] More info: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3683
```

Given this fact, I'll close this issue. Feel free to mention if the issue persists on a bare-bones setup with the same client version as the server and we may reopen this.

**Comment by JavituRec** [comment]
But let's see, if the server is 1.21.1 and the user connects with 1.21.2, 1.21.3 or 1.21.4 it should not be a problem. I use Viaversion so that the user can connect with those versions is normal and I only allow to connect with higher versions and not earlier so there should not be problems. 

If you close this and there is no response from @LoneDev6  you will most likely leave a bad patch when this problem should be fixable. In fact if you were really concerned you would have reported the following: https://github.com/PluginBugs/Issues-ItemsAdder/issues/4237

**Comment by Andre601** [comment]
> But let's see, if the server is 1.21.1 and the user connects with 1.21.2, 1.21.3 or 1.21.4 it should not be a problem. I use Viaversion so that the user can connect with those versions is normal and I only allow to connect with higher versions and not earlier so there should not be problems.

You personally don't get the main point. 1.21.4 despite being a patch version by SemVer standard, is a breaking change by Mojang Standards.
They decided a while ago that even smaller updates like a patch bump can have breaking changes. And 1.21.4 is such a change.
This doesn't include the fact, that Minecraft by nature is a single-version game. The Server itself does not natively support 1.21.4 players joining a 1.21.3 server. If you want to proof me wrong, start a vanilla server (Or paper with zero plugins) and try it yourself.

That players with 1.21.4 can join your server is solely ViaVersion's doing, which is also where we hit the main issue.
ViaVersion is doing all the stuff to make newer versions be able to join old ones. As such is it in ViaVersion's responsability to deal with and fix and issues that appear on client versions that aren't the server's version.
ItemsAdder *could* try and work with ViaVersion in certain ways for support, but it's not a primary focus nor is it always a possible fix on ItemsAdder's end.

This is why ItemsAdder prints messages on start and when players with differing versions join, that you shouldn't report bugs with those players, as it is inherently an issue with ViaVersion and not ItemsAdder.
ItemsAdder isn't the plugin constantly rewriting packets for the player. It's ViaVersion...

> If you close this and there is no response from [@]LoneDev6 you will most likely leave a bad review when this problem should be fixable. In fact if you were really concerned you would have reported the following: #4237

This text makes no sense, no matter how I move it... If you used a translator, use a competent one like DeepL.
But, if this is meant to say "If this issue remains closed and I won't get a reply from LoneDev, I'll leave a bad review", then this just shows your bad attitude towards us.
You basically try to blackmail us into forcing ourself to fix an issue that may not be ItemsAdder's fault, because you think a bad review would make things different (Spoiler: It doesn't).

I leave it to LoneDev to deal with this further. You probably ignore me anyways.

**Comment by JavituRec** [comment]
I know that ItemsAdder would not support older versions which seems logical to me but I think that those like me who try to keep the server updated (whenever possible you know that sometimes it is complicated and more if it is not a mini game) should have a more empathetic support because you do not know if my server has 10 people or 1000 playing and thus the hours of work that this entails. Regardless of this, I'm just trying to find a solution and close the ticket I don't think it's an action that will solve the problem or at least try to. That said, sorry if my translator is not doing it correctly and there was a misunderstanding but I would like to find a solution to this problem.

PS: I support ItemsAdder, that's why I bought it.

**Comment by LoneDev6** [comment]
Try to regenerate your resourcepack, it might not be correctly updated this is why you see paper and not the custom texture.
Also check that your warps plugin is correctly set up, maybe it has no custom model data set, or has a wrong custom model data.
Consider contacting the author of your warps plugin.
This is not an ItemsAdder bug and has nothing to do with ProtocolLib by the way.

**Comment by JavituRec** [comment]
This happens in all menus so I thought it might be ItemsAdder problems with the latest version 1.21.4. However I have investigated and updated plugins. No texture pack and these roles are still showing up in all menus.

![Captura de pantalla 2024-12-21 022551](https://github.com/user-attachments/assets/e9dfeb9c-fc84-444f-a759-7aeba2c40e8e)

I have also done a clean install along with the texture pack and it is still at the same point.

![Captura de pantalla 2024-12-21 023546](https://github.com/user-attachments/assets/87e9312d-ee02-438b-82a7-18f221d66924)
