### ISSUE TITLE
Configuration does not work

### ISSUE THREAD

**Issue by euj3ne** [PluginBugs/Issues-ItemsAdder#4283]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [X] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### What happened?

Good afternoon. I want to make that resourcepack was on all servers, found a wiki about ‘Single resourcepack Bungeecord different features’, as well as read in the wiki on the site. But I can't do it. On the first server, for example ‘Hub’, I have Self-Host, from where the resourcepack is downloaded to the player. I copied the configuration completely on the server, for example, ‘survival’, put there nohost, going to it, the configuration of the resourcepack works, but does not display the textures themselves.
However, if I put them in the Minecraft directory, everything works except the items, because you can not specify minecraft:item. When I make another directory, for example survival:item, then nothing works at all.

### Steps to reproduce the issue

I think fixing the wiki.

### Server version

Current: git-Plazma-"264f7cf" (MC: 1.19.4)*
Previous: git-Purpur-1171 (MC: 1.16.5)

### ItemsAdder Version

ItemsAdder version 3.6.6-legacy

### ProtocolLib Version

ProtocolLib version 5.3.0

### LoneLibs Version

LoneLibs version 1.0.63

### Full Server Log

https://mclo.gs/

### Error (optional)

```shell
No errors.
```

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: "survival"
items:
  air:
    display_name: "&r"
    permission: items.air
    resource:
      material: paper
      generate: false
      model_path: item/air
```

### Screenshots/Videos (you can drag and drop files or paste links)

server: hub
![image](https://github.com/user-attachments/assets/7fb41be9-7635-4840-ba40-04ca570ba970)

server: survival
![image](https://github.com/user-attachments/assets/adf1b1b4-7825-463c-ab06-7005bc3c9d79)

**Comment by Andre601** [comment]
Using self-host won't work here, as it is limited to that particular server and won't apply on the others.
It's why the wiki page you mentions tells you to set no-host on **all servers**.

There really isn't more that we can tell you here. The wiki page is as simple as it can be in explaining what to do here.
What is important is:

- You have no-host enabled on all ItemsAdder instances.
- You created a single resource pack containing all textures and files for all the servers combined (Not just a single server), which is why you should make it on a local test server.
- You uploaded the resource pack to a site like Dropbox, Google Drive or similar that offers a direct download link (meaning opening it in browser downloads the zip file)
- You copied the ItemsAdder jar file **and** the ItemsAdder folder from your local server to all servers that need it, and configured each to use the items the server should have.
- You use a proxy plugin to apply the resource pack on the players across the servers.

There really isn't anything else we can tell you here. It requires work and understanding some parts of making and hosting resource packs. Nothing we can help you with here and nothing for this issue tracker.
