### ISSUE TITLE
[BUG] Not all Emojis loading

### ISSUE THREAD

**Issue by xSorch** [PluginBugs/Issues-ItemsAdder#601]
**Describe the bug**
For some reason when a few of my players connect, not all the emojis are loaded properly, which makes them show up a [] white bracket for some reason. That issue comes and go for a few players, including myself rarely. 
No itemsadder errors sorrounding this issue in console or my logs either.

**Screenshots**

**Info (please complete the following information):**
 - Server version: 1.16.5
 - Client version: 1.16.5
 - Plugin version: 2.1.27

**Comment by xSorch** [comment]
Here is another example, doesn't always turn into brackets.
https://gyazo.com/8fd0f16b951ad4470401cd9ee16f316c
Both users have the server texture loaded, and no errors, but for some reason the user on the left screen doesn't see all emojis. I've realised that after I OP the user on the left side and he rejoins, then I post the emoji, it works fine. So guessing there is a perm I am missing? As far as I am aware of, there are no permission for seeing emojis, only posting them.

**Comment by LoneDev6** [comment]
About the white [] it could be for some reasons (it's not brackets but a square actually = missing character):
- resourcepack failed to load some of the emojis because some of them have uppercase or bad characters in their png file name
- resourcepack failed to load some emojis for some other reason

I suggest you to open a ticket on my discord and ping me, provide me your whole ItemsAdder configuration folder (zip it) so I can test (don't worry I don't care about stealing content from my customers)



> 
> 
> Here is another example, doesn't always turn into brackets.
> https://gyazo.com/8fd0f16b951ad4470401cd9ee16f316c
> Both users have the server texture loaded, and no errors, but for some reason the user on the left screen doesn't see all emojis. I've realised that after I OP the user on the left side and he rejoins, then I post the emoji, it works fine. So guessing there is a perm I am missing? As far as I am aware of, there are no permission for seeing emojis, only posting them.

yes probably they are missing some [perm](https://itemsadder.plugin.ga/plugin-usage/permissions), for example if the emojis is named smile you must set:
`ia.user.image.use.smile`

and also set this to allow them to use the emojis in chat
`ia.user.image.chat`

![immagine](https://user-images.githubusercontent.com/27242001/105494696-78c8d700-5cbb-11eb-83d9-169c8739d3e2.png)

**Comment by LoneDev6** [comment]
problem was:
> resourcepack failed to load some of the emojis because some of them have uppercase or bad characters in their png file name

**Comment by xSorch** [comment]
Didn't solve the full problem, still seem to be happening here and there, just less. 
The issue with those permissions is that once you give any of those, regular players are also able to use emojis. Would be nice if it was a one way perm or set to default that people without the use perm can see them. Because on my server, the use of emojis is for premium users meaning that default players can't see the emoji. Only Premium ranks can see and use them, so it's either only premium being able to see them and not default, or everyone including default being able to see and use them. https://gyazo.com/1a6723d3daffa466af34b17aac488fd7

**Comment by xSorch** [comment]
Also having multiple complaints of having issues connecting with LunarClient.

**Comment by LoneDev6** [comment]
I will post an update today, please install it and let me know, thanks!
You can remove emojis permissions the permissons to players that are not allowed to use the premium emojis.

**Comment by LoneDev6** [comment]
> 
> 
> Also having multiple complaints of having issues connecting with LunarClient.

be more specific, like what happens? any error?

please open another report as they seem not to be connected (emoji problema and LunarClient client problem).
Open a new issue after you got any valid information for me to fix the LunarClient problem, thanks
