### ISSUE TITLE
[BUG] Emoticon

### ISSUE THREAD

**Issue by istarengwa** [PluginBugs/Issues-ItemsAdder#619]
**Describe the bug**
Emojis are no longer displayed, grades :admin:, :helper: not work. it doesn't work in the chat, in the signs, in the anvil....
I haven't changed anything to my resource pack or my item pack for a very long time, it was still working very well 1 week or 2 ago, I don't know since she updated it no longer works

**Info (please complete the following information):**
purpurclip-964 (1.16.)  (paper)
itemsadder 2.1.29

**Comment by istarengwa** [comment]
everything works on version 2.1.27 of the plugin

**Comment by LoneDev6** [comment]
Interesting, well did you set the correct permissions to your players?
Do they work if issues by OP players?

Thanks for the collaboration

**Comment by istarengwa** [comment]
players have the perms correctly, and I am still op, and I had done the test, and it didn't work anymore, when I put back the old version (2.1.27) everything was working normally again

**Comment by xSorch** [comment]
Same issue.

**Comment by LoneDev6** [comment]
Are only ranks not displaying in the chat?
You can use PlaceholderAPI to show ranks to everyone even if they have no permission, for example %img_admin% instead of :admin: , [check here for more info](https://itemsadder.plugin.ga/plugin-usage/using-font_images-emojis-everywhere)


For example if your players write :smile: in chat does it works? It should work normally if you gave them there permissions:
ia.user.emoji.use.smile (access the smile emoji)
ia.user.emoji.gui (use /e command to see emojis book)
ia.user.emoji.hints (suggest emojis when using /e and TAB complete)
ia.user.emoji.chat (replace emoji text :smile: etc in chat)
ia.user.emoji.command (replace emoji text :smile: etc in commands)
ia.user.emoji.sign (replace emoji text :smile: etc in signs)
ia.user.emoji.book (replace emoji text :smile: etc in books)

**Comment by istarengwa** [comment]
I already have PlaceHolderAPI

nothing is displayed in the chat, neither the rankings nor the emojis, but on the old versions of the plugin everything works

whether it is a player or an op admin, write it from :smile: only displays :smile: to everyone, no smiley.

I didn't leave the latest versions of your plugin active on my server, because players can no longer use emojis, so they have all their player perms, and admins have all perms since they are op, that did not work, however.

**Comment by LoneDev6** [comment]
Thanks a lot for the infos.
I wrote a tutorial for common uses for ranks :)
https://itemsadder.plugin.ga/plugin-usage/adding-content/advanced/ranks-textures-tags

I fixed your issue in the new update, please let me know.

**Comment by istarengwa** [comment]
ItemsAdder 2.1.30 : [url=https://zupimages.net/viewer.php?id=21/05/sgvx.png][img]https://zupimages.net/up/21/05/sgvx.png[/img][/url]

ItemsAdder 2.1.27 : [url=https://zupimages.net/viewer.php?id=21/05/hcyt.png][img]https://zupimages.net/up/21/05/hcyt.png[/img][/url]

**Comment by LoneDev6** [comment]
let me see your config.yml


> For example if your players write `:smile:` in chat does it works? It should work normally if you gave them there permissions:
> ia.user.emoji.use.smile (access the smile emoji)
> ia.user.emoji.gui (use /e command to see emojis book)
> ia.user.emoji.hints (suggest emojis when using /e and TAB complete)
> ia.user.emoji.chat (replace emoji text `:smile:` etc in chat)
> ia.user.emoji.command (replace emoji text `:smile:` etc in commands)
> ia.user.emoji.sign (replace emoji text `:smile:` etc in signs)
> ia.user.emoji.book (replace emoji text `:smile:` etc in books)

^^^^^ I did some tests and latest version works fine, so there might be a mistake in permissions or config.yml

**Comment by LoneDev6** [comment]
set
```yml
font_images:
  chat:
    enabled: true
    replace-only-packets: true
```

**Comment by istarengwa** [comment]
thx it's work for last version =)
