### ISSUE TITLE
[Suggestion] Recipes in Recipebook (Routed via "Gust")

### ISSUE THREAD

**Issue by ArgonGaming** [PluginBugs/Issues-ItemsAdder#665]
https://cdn.discordapp.com/attachments/629310133272576000/807176417183924244/unknown.png

**Describe the solution you'd like**
Custom Recipes having a TOGGLEABLE option to show in the recipe book makes it much easier than players having to use a command to open a completely separate recipe book just for custom items. It will feel more vanilla-like and flow with the gameplay better.

**Additional context**
Suggested by Gust, wanted to resuggest here incase missed. It was too good of a feature to pass up.

**Comment by SirCraftypants** [comment]
Not sure you can add custom recipes to vanilla mc's recipe gui but there's definitely options. Like creating a book that can be held in hand and clicked to open the IA recipe gui or a custom recipe gui so no need to use the command. Some would argue the command is quicker but each to their own.

**Comment by ArgonGaming** [comment]
> Not sure you can add custom recipes to vanilla mc's recipe gui but there's definitely options. Like creating a book that can be held in hand and clicked to open the IA recipe gui or a custom recipe gui so no need to use the command. Some would argue the command is quicker but each to their own. You could do this as an Addon to Itemsadder by using the free DeluxeMenus plugin along with IA. You could literally have a categories title gui leading to each recipe, would take a while adding all the recipes but you wouldn't have to create loads, just the main gui menu and a recipe for each category as an example. You just use a blank texture the same color as the gui frame to blank out all the unused slots, add navigation buttons etc.

The point is for it to feel 100% vanilla, no extra GUIs or such. Luckily, this is 100% possible, and likely has a clever work around to make it work, Going to reference Origin Realms again for this one though 😂 It would be an amazing option for ItemsAdder

**Comment by LoneDev6** [comment]
This request was asked a lot of times and I always have to link this issue report: https://github.com/PluginBugs/Issues-ItemsAdder/issues/6

The bug kept reappearing on each spigot/paper update as you can see by the amount of notes I left.
The final note is about a complete removal of the itemsadder recipes from recipe book which fixed the issue completely.


For now I have no way to add custom recipes to vanilla recipe book because it generates tons of dupe bugs which I cannot fix due to the lack of API on the recipe book + Minecraft codebase of the recipe book stinks

**Comment by SirCraftypants** [comment]
> 
> 
> This request was asked a lot of times and I always have to link this issue report: #6
> 
> The bug kept reappearing on each spigot/paper update as you can see by the amount of notes I left.
> The final note is about a complete removal of the itemsadder recipes from recipe book which fixed the issue completely.
> 
> For now I have no way to add custom recipes to vanilla recipe book because it generates tons of dupe bugs which I cannot fix due to the lack of API on the recipe book + Minecraft codebase of the recipe book stinks

I guessed it wouldn't be possible to add to vanilla's recipe gui and said as much, i attempted it with a mod but it just caused problems. I think my Deluxemenu's custom recipe book is your best option Argon, then you can use an event on a book to open it or something along those lines.

**Comment by LoneDev6** [comment]
> I guessed it wouldn't be possible to add to vanilla's recipe gui

It's possible to add recipes to the vanilla GUI as they are automatically added when any plugin registers them into the game.
The problem comes when a recipe uses ItemStacks and not only Materials. This causes a lot of problems and dupe bugs, that's why I decided to hack Spigot recipes manager and remove ItemsAdder recipes from the recipe book

**Comment by SirCraftypants** [comment]
> 
> 
> > I guessed it wouldn't be possible to add to vanilla's recipe gui
> 
> It's possible to add recipes to the vanilla GUI as they are automatically added when any plugin registers them into the game.
> The problem comes when a recipe uses ItemStacks and not only Materials. This causes a lot of problems and dupe bugs, that's why I decided to hack Spigot recipes manager and remove ItemsAdder recipes from the recipe book

yeah, i meant not possible because it causes issues.
