### ISSUE TITLE
[Suggestion] Compatiblity with RealisticWorldGenerator block generation

### ISSUE THREAD

**Issue by Venterok** [PluginBugs/Issues-ItemsAdder#675]
**Is your feature request related to a problem? Please describe.**
RealisticWorldGenerator has the ability to spawn ores/blocks from other plugins. 
But it doesn't work with itemsadder. The blocks have a custom texture, but when breaking it is a regular mushroom
Here's what support RWG said to me-
![image](https://user-images.githubusercontent.com/67825103/108363143-a7c46100-7205-11eb-8ede-1dc9d3d5875d.png)
![image](https://user-images.githubusercontent.com/67825103/108363189-b1e65f80-7205-11eb-8749-d7ddec2159d8.png)

**Describe the solution you'd like**
The blocks were generated from Items adder.

**Describe alternatives you've considered**
Add a parameter to disable checking the block is from items adder or not (?)
(Maybe it's already there but I'm stupid for not finding it)

**Additional context**
Guide how create simple custom block spawn in RWG:
https://docs.oraxen.com/compatibility/world-generators/realisticworldgenerator
RealisticWorldGenerator spigot page:
https://www.spigotmc.org/resources/realisticworldgenerator-1-8-8-1-16-x.15905/

**Comment by LoneDev6** [comment]
ItemsAdder doesn't rely just on blockstates to avoid dupe bugs and similar (so surely Oraxen surely suffers of this problem).
Mushroom blocks are known to change states in some occasions even if the events are cancelled, that's why ItemsAdder also saves the custom block data inside a custom region file of the world, to avoid these possible dupe bugs and ignore "glitched" blocks.


The only way for me to add ItemsAdder compatibility to RWG is to ask them to use my api to spawn custom blocks.
The [API is freely available](https://github.com/LoneDev6/API-ItemsAdder/blob/master/src/main/java/dev/lone/itemsadder/api/CustomBlock.java#L13) without owning the plugin.

If they don't want to implement itemsadder compatibility on their own I have to do something else, which SHOULD work:
- add an option to disable the `fix-glitched-blocks` behaviour from the world where you want custom block to be spawned by RWG, to avoid IA from resetting mushroom blocks faces all to TRUE
- add an option called (for example) `convert-spawned-mushroom-blocks-to-custom-blocks` to basically convert spawned mushroom blocks (by RWG) to IA custom blocks and register them correctly on chunk load event.


This solution has some downsides:
- possible dupe bugs
- support only mushroom blocks/chorus and not TILE blocks
- CPU overhead as I have to scan all the chunk blocks on chunk load which doubles the processing time (as I have to scan the chunk another time, the first time is done by RWG on its own block spawn code)

**Comment by Venterok** [comment]
I passed the issue link to their discord. We will wait for an answer

**Comment by Venterok** [comment]
answer
![изображение](https://user-images.githubusercontent.com/67825103/108377520-2b397e80-7215-11eb-9a24-99553225d1c6.png)

**Comment by LoneDev6** [comment]
Very good, thanks.
You can also ask them to contact me via PM on Discord if needed LoneDev#7444

**Comment by Venterok** [comment]
Have you been able to contact the developers of RWG?

**Comment by Lauriichan** [comment]
I didn't contact the developer of ItemsAdder as the API seems to be straight forward, I'm currently working on the update and I hadn't time the last few days but it will be compatible soon (I hope xD)

**Comment by LoneDev6** [comment]
> 
> 
> Have you been able to contact the developers of RWG?

Yes and they're working hard to add compatibility, I'd wait for an update from them and close this issue for now
