### ISSUE TITLE
[Suggestion] Will itemadder consider compatibility with deluxemenus next

### ISSUE THREAD

**Issue by xiaobailoves** [PluginBugs/Issues-ItemsAdder#684]
**Is your feature request related to a problem? Please describe.**
If Itemadder is compatible with deluxemenus. It would be possible to create a lot of nice gui

**Describe the solution you'd like**
https://docs.oraxen.com/compatibility/trmenu-custom-inventories
I hope you will take a look at it, the final result will look like this

**Describe alternatives you've considered**
No

**Additional context**
![2020-03-11-203342_647x667_escrotum](https://user-images.githubusercontent.com/71917424/108591221-7c558980-735f-11eb-9494-074790724a69.png)

**Comment by LoneDev6** [comment]
Hello,
itemsadder is already compatible with this plugin.
In order to add a custom texture to your GUI you have to
- create a texture like one of the ones already created here: `plugins\ItemsAdder\data\resource_pack\assets\mcguis\textures\font\gui`
(create it in your namespace, not in my namespace "mcguis".
For example create a new texture called `my_gui`.
- then create a custom GUI with your plugin and change the GUI title to `:offset_-16::my_gui:`. This retextures the title of the GUI creating a very big texture and shifts it back of 16 pixels (which is the default hardcoded Minecraft shift value for inventory titles).

Note that this method is better as ItemsAdder is not creating custom GUI textures like Oraxen or similar plugins.
This allows you to retexture inventories without using two retextured items and put them in the inventory.


Let me know if something is not clear or if you encounter any problem.

Another solution would be to ask the plugin author to contact me directly so we can collaborate on adding compatibility
