### ISSUE TITLE
Resource pack not loading, and freezing players

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#702]
Bug: Resourcepack failing to load

The bug happens when people try to join the server with resource packs enabled, it shows a screen that says something like "Downloading resource pack" and the below that it shows a percentage, but stops and freezes the game when it reaches 100%, the player cannot press esc. and has to be kicked from the server to leave.

Expected behavior: the resource pack would work

I do not currently have a screenshot from one of my players

Info:
 - Server version: paper 1.16.5
 - Client version: Vanilla 1.16.5
 - Plugin version: 2.1.41

Additional context:
The resource pack works for me , but I am hosting the server on my own computer, and that may be why, I am also hosting the resource pack on my own computer. There is no Error message either, it simply says "%Player_name% failed to load resource pack.

**Comment by LoneDev6** [comment]
This happens when the pack fails to load for one of these causes:
- link is not reachable
- link port is not opened (port set in the config.yml)
- malformed zip file
- web page is not a direct link
After you made sure that the resourcepack link is reachable from your browser please open a ticket on my discord server and provide your full server log and itemsadder resourcepack.

**Comment by BookWyrm114** [comment]
Thank you, I was able to get the resource pack working now.

**Comment by LoneDev6** [comment]
What was the issue? Thanks a lot

**Comment by BookWyrm114** [comment]
Actually, I was not able to figure out what was causing the problem, I tried uploading the resource pack to Dropbox and using that link instead, and that seems to work now, I think it may just be a problem with my computer, I’m also still on Java 8, so that might be it
