### ISSUE TITLE
[Suggestion] Change the "Custom GUI Code" of Skript's expert users page

### ISSUE THREAD

**Issue by danielzinh** [PluginBugs/Issues-ItemsAdder#708]
**Is your feature request related to a problem? Please describe.**
after various tests, i created a better code, i sugest you change to then

**Describe the solution you'd like**
My code: https://pastebin.com/GwSvFnEQ

**Describe alternatives you've considered**
this code is better and does not need to save the player's name in any array variable (it causes bugs in several cases), besides being simpler, optimized and the standard used by almost all code creators, the famous "on inventory click"

**Additional context**
I hope you enjoy it, it took me a long time to find an answer, it was in my face all the time, but I found it so simple that I didn't even think about testing it, lmao.

@edit

any questions, can you tell me, Discord: DanielZinh#7616

**Comment by danielzinh** [comment]
note: works with all skript versions that supports skript-mirror.

**Comment by LoneDev6** [comment]
Hello!
Thanks, but this is not a very clean way since all inventories that contain "MENU NAME" in the title would work as custom GUI and it's not very good.
My code makes sure that it's 100% a custom GUI since I add the player to an array when they use the command, and then check later.

Thanks anyway for the code, I appreciate your dedication
