### ISSUE TITLE
[BUG] With a large online and low TPS, the custom ores begin to lag

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#745]
With a large online and low TPS, the custom ores begin to lag, see video.. https://youtu.be/9KHbqksWkBk

**Comment by LoneDev6** [comment]
Please avoid deleting the issue template.

Post a timings report of **when the issue happens**.
Also specify the Ping of the user that is trying to mine the block. Since the custom block breaking animation is server-side it may not be smooth, but the block will be mined if you keep pressing the left click mouse, don't stop clicking.
