### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Antonioxr** [PluginBugs/Issues-ItemsAdder#774]
**Is your feature request related to a problem? Please describe.**
Would be nice to have blocks in which can add effects to a player for example one can give you poison like its a radioactive block another can make you bounce in x-height as the main issue is many plugins either allow you to do that on a singular block type or the limit you on the block type and that becomes a problem when all items are barriers 

**Describe the solution you'd like**
add a variable to the config when you stand on a block you can add effects and actions to it

**Comment by The-Gust** [comment]
Don't forget about video example
https://www.youtube.com/watch?v=gYaBr3IRmaE

**Comment by LoneDev6** [comment]
Actually this won't be implemented because of how would make the server lag, checking for near blocks each time a player moves is very resource intensive with the current Spigot API, so for now this cool suggestion have to be rejected, I'm sorry.

You're free to implement that in an addon using the ItemsAdder API, but surely you'll find out that it will slow down the server
