### ISSUE TITLE
[BUG] visual block change bug & double sound placing block

### ISSUE THREAD

**Issue by Venterok** [PluginBugs/Issues-ItemsAdder#828]
**Describe the bug**
when the block is placed, a double sound is played. When breaking a block under a custom block, the texture changes for a couple of seconds

**To Reproduce**
more details are shown in the video
1. Place a custom block on a regular one
2. Break the block under custom block
3. See visual bug

**Video**
Video showing two bugs
https://cdn.discordapp.com/attachments/441244803527606282/831185718369845258/Untitled-1.mp4

**Info (please complete the following information):**
 - Server version: Purpur 1.16.5
 - Client version: Optifine 1.16.5
 - Plugin version: 2.2.12

**Comment by LoneDev6** [comment]
1. provide your custom block complete configuration file
2. the visual bug can't be fixed, I can't send the packet to the client in 0.00001ms, there is always a delay due to how internet works. Client predicts changes so that's why you see the block changing and then itemsadder reverting the change.
