### ISSUE TITLE
add backpack as a Armor stand on a Head 

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#859]
- Back back - Armor stand ride the player
- Sorry About my English
![unknown](https://user-images.githubusercontent.com/68678154/115923991-65c2d000-a47f-11eb-8998-32247f9dd4fe.png)

![image](https://user-images.githubusercontent.com/68678154/115925229-1a112600-a481-11eb-99fd-2dc290584588.png)

Example video -i know that you have been added a backpack but it's waving, not stable , I think this video will give you a Very Good Example but he is using a Command Block .
https://www.youtube.com/watch?v=d9JSx-R1EXQ

**Comment by yebanme** [comment]
Look forward to the realization of this function

**Comment by LoneDev6** [comment]
It's possible and I've already coded that in 2016 and dropped the code.
The reason was performance issues.
Imagine having to rotate the armorstand every tick for every player around to make sure it's not desync, very laggy.

**Comment by yebanme** [comment]
There is no doubt that compared with the current scheme, the lag is certain. In order to ensure the stability of the plug-in, there is no problem not to use this method. If you can add this method as another scheme for plugin users to choose,is to sacrifice speed for beauty,maybe you can let users choose the way they want

**Comment by SNokerYT** [comment]
i think it's the same thing on plugin TAB also plugin tab using armor stand on ahead without any problem  Meaby if you can 
Connect them together plugin TAB with item adder you will fix this problem and will not be any performance problem and make it to be able to use this Feature you have to use plugin tab = 
required plugin Tab | https://www.spigotmc.org/resources/tab-1-7-x-1-16-5-free-version.57806/ 
![image](https://user-images.githubusercontent.com/68678154/115960439-c26ecb00-a511-11eb-93ee-7c416c4c74ed.png)

**Comment by SNokerYT** [comment]
Even you can add this Feature without Need to connect it with tab plugin, you just need to know how they using Armorstand on a head without any issue with performance

**Comment by xalixilax** [comment]
> Even you can add this Feature without Need to connect it with tab plugin, you just need to know how they using Armorstand on a head without any issue with performance
But is it possible that it's not checked every tick? Since this is floating over the head it's fine if it get desync a little. 

Maybe a suggestion. Some entity can be mounted (pig/horse) Is there a way to make the armor stand "mount" the player? I know this i possible to make any mobs ride any mobs but i don't know if this is possible with things like player and armor stand.

**Comment by kikolco** [comment]
Hey everyone, I'm the one who made the video in the original post and I am really not sure how to fix the lag issue, since I am not experienced in Java coding; but I can say that I am using my system with command blocks and it has not given me any lag problems yet. (Although I have only tried it with up to 30 players)

I do hope that this feature

**Comment by yebanme** [comment]
It's been a while, and I don't know if this proposal will be adopted,or if enough people want to have this feature, it will be added to the development plan

**Comment by yebanme** [comment]
It's been a while, and I don't know if this proposal will be adopted,or if enough people want to have this feature, it will be added to the development plan

**Comment by taleno503** [comment]
We need it, please

**Comment by SNokerYT** [comment]
Please. LoneDev, it will be an amazing Feature if you add it to the plugin 🥰
We waiting for your answer from 18 days 💖

**Comment by yebanme** [comment]
A month has passed. Has anyone found an alternative way to achieve it

**Comment by SNokerYT** [comment]
i Really Need it too So much but I Don't know What to do

> A month has passed. Has anyone found an alternative way to achieve it

**Comment by LoneDev6** [comment]
> 
> 
> A month has passed. Has anyone found an alternative way to achieve it

As you can see there are more than 78 different requests, I know a month passed, everyone is waiting.
I hope to find the time to implement this but I don't think it's a good idea as it will cause a lot of server lag.

**Comment by LoneDev6** [comment]
> 
> 
> i think it's the same thing on plugin TAB also plugin tab using armor stand on ahead without any problem Meaby if you can
> Connect them together plugin TAB with item adder you will fix this problem and will not be any performance problem and make it to be able to use this Feature you have to use plugin tab =
> required plugin Tab | https://www.spigotmc.org/resources/tab-1-7-x-1-16-5-free-version.57806/
> ![image](https://user-images.githubusercontent.com/68678154/115960439-c26ecb00-a511-11eb-93ee-7c416c4c74ed.png)

The main difference is that the TAB plugin doesn't rotate the armorstand.
To make the custom backpack I have to rotate the armorstand on each server tick, so each 50ms for each player that wears a backpack.
Server will explode

**Comment by SNokerYT** [comment]
it Should Not Rotate also
you Don't have to Rotate the armor stand on Each server tick it should only stick on the head 
and but the pack back on head it's the same way of plugin |Tab|
the Difference is that you just have to put the pack back on a head of the armor stand  
- if I'm saying something wrong I'm sorry I don't have enough experience with plugins 😁
For Example | Form What I see it's the Same way of plugin | TAB | ,I don't know 😅
![image](https://user-images.githubusercontent.com/68678154/119228073-8b400980-bb11-11eb-85e5-37bffebb9889.png)
![bug3dwadw](https://user-images.githubusercontent.com/68678154/119228167-06092480-bb12-11eb-8600-39de3a90c283.gif)

**Comment by yebanme** [comment]
My idea is the same as SNokerYT. you just need to mount the armor stand on the player's head, and you don't need to operate other content, maybe like this plugin [HoldEntities ](https://www.spigotmc.org/resources/holdentities.80576/)

**Comment by LoneDev6** [comment]
I have to update rotation on each server tick, trust me.
Try to use command blocks and put an armorstand as passenger of your player, then walk around and rotate.
Armorstand won't follow your rotation, it will stand still keeping its rotation unchanged (relatively to world space).
I don't have time to make a video but you're free to make your own tests which will 101% reveal to be as I pointed out

**Comment by yebanme** [comment]
> I have to update rotation on each server tick, trust me.
> Try to use command blocks and put an armorstand as passenger of your player, then walk around and rotate.
> Armorstand won't follow your rotation, it will stand still keeping its rotation unchanged (relatively to world space).
> I don't have time to make a video but you're free to make your own tests which will 101% reveal to be as I pointed out

That's right, the armor stand did not follow the player's rotation, I tested it. If the plugin implements this function, it is necessary to frequently correct the angle of each player's armor stand.

Hope to find a better way to achieve this function

**Comment by LoneDev6** [comment]
I doubt sincerely.
OriginRealms is made to support few players, ItemsAdder is for big networks and can easily hold more than 60 players.
I can't add this feature for now due to its intensive packets usage and possible visual/server lag.

Maybe in the future, for now the constant packets sending solution is bad

**Comment by Dkavila** [comment]
Maybe it can help you... Instead of putting an armorstand on the head try changing the item's position via JSON. On my server I did it that way and it worked perfectly. The player places the item in their off or main hand and the backpack is positioned on their back. This works with any item created.
![image](https://user-images.githubusercontent.com/43159733/122006341-16b55f00-cd8d-11eb-996a-e5275ba4ada7.png)

You can position any item easily using Blockbench, Cubik Studio and others... Later generate the JSON with the position and put in your resource pack.

**Comment by SNokerYT** [comment]
> Maybe it can help you... Instead of putting an armorstand on the head try changing the item's position via JSON. On my server I did it that way and it worked perfectly. The player places the item in their off or main hand and the backpack is positioned on their back. This works with any item created.
> ![image](https://user-images.githubusercontent.com/43159733/122006341-16b55f00-cd8d-11eb-996a-e5275ba4ada7.png)
> 
> You can position any item easily using Blockbench, Cubik Studio and others... Later generate the JSON with the position and put in your resource pack.
> 
> By the way, armorstands always generate a lot of lag :p

you have to know that isn't a professional way to do it, your idea it's the same of | item adder backpacks |
We don't need the hand movement, we need it to be centered in the back and this means we will need to use armor stand to do this job

**Comment by LoneDev6** [comment]
Conversation locked due to the excessive amount of repetitive messages.
This may be implemented in a future update, but as I said (and I also provided proofs) this will surely cause insane lag on the server and even if other servers have this feature it's not a reason to make ItemsAdder a lag machine

**Comment by LoneDev6** [comment]
https://cosmeticscore.devs.beer/
