### ISSUE TITLE
[Suggestion] Allowing owner to set which icon go with which unicode

### ISSUE THREAD

**Issue by xalixilax** [PluginBugs/Issues-ItemsAdder#863]
Adding possibility the the owned to set a selected a selected Unicode to be replaced by a custom icon. The main reason is by pressing windows key + ; you can select an emote you want to add to the chat. 

The issue is that when you create an emote, it is given a random Unicode. Being able to set a Unicode for each emoji could allow us to sync the windows emoji panel with the Minecraft chat. Could be useful especially since a lot of emoji are already set and would easily allow user to add emoji without having to learn their names.

**Comment by LoneDev6** [comment]
I wish this was possible, I already had this idea in the first days of development but it's not possible.
Emojis use 2 unicode values to rappresent a single emoji, Minecraft supports only 1 unicode value per character, so I can't, that's why I use other unicode values, different from the normally used ones.
