### ISSUE TITLE
[Suggestion] Possibility to use ItemsStack Serialization

### ISSUE THREAD

**Issue by NessunoMC** [PluginBugs/Issues-ItemsAdder#883]
Add the ability to use ItemsStack Serialization in the ItemsAdder configuration. For example, in the case of Trading Machines it would be very useful to be able to use items managed by other plugins.

**Comment by LoneDev6** [comment]
Very hard to implement and unreliable.
An example is Shopkeepers which also has this kind of issues about items matching not always working correctly when NBT changes.

One thing I'd do it creating an issue report on Shopkeepers' Github page and suggest to add ItemsAdder compatibility, like [this one](https://github.com/Shopkeepers/Shopkeepers/issues/773) for Oraxen, even tho I doubt they'll add that since 2 years passed since this issue report, for example.
