### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by a469** [PluginBugs/Issues-ItemsAdder#921]
Can you add ItemsAdder to be compatible with BlepFishing? I want to use ItemsAdder to make recipes for fish and use BlepFishing to realize the fishing function, but because the fish caught are not the items in ItemsAdder, I can’t use synthesis. I have tried Use CustomCrafting, but he does not have the option to only recognize CustomModelData. Because the lore of the fish in BlepFishing is random, it is impossible to create the same recipe for the same type of fish with different lengths. You can add fish that are compatible with BlepFishing (among them The fishes are made of salmon with CustomModelData) become items in ItemsAdder, and can I use the recipe normally? Or can you create a recipe that only recognizes CustomModelData?The following two screenshots are the fish in BlepFishing
![image](https://user-images.githubusercontent.com/40757206/119837381-0fb7d100-bef2-11eb-8f23-7f569d42bb75.png)
![image](https://user-images.githubusercontent.com/40757206/119837419-16dedf00-bef2-11eb-841c-52147741c464.png)

**Comment by LoneDev6** [comment]
You can send this Github issue link to the Blep Fishing author: https://github.com/PluginBugs/Issues-ItemsAdder/issues/921

Hello!
If you want you can add support to ItemsAdder items in your plugin easily! [I added you to the buyers list ](https://www.spigotmc.org/resources/%E2%9C%85must-have%E2%9C%85-itemsadder%E2%9C%A8custom-items-huds-guis-mobs-3dmodels-emojis-blocks-wings-hats-liquids.73355/)for free so that you can make your tests.
ItemsAdder API is very easy to use: https://itemsadder.plugin.ga/developers/java-api

**Comment by LoneDev6** [comment]
I contacted them, I wait for update

![immagine](https://user-images.githubusercontent.com/27242001/121040112-efb9c480-c7b1-11eb-9935-4b38cab4cdeb.png)
