### ISSUE TITLE
[I do not know this is a bug or a suggestion] Very broken shit is related to the block cache

### ISSUE THREAD

**Issue by Venterok** [PluginBugs/Issues-ItemsAdder#922]
We have a very fat problem on the server related to Itemsadder, namely with the cache of custom blocks. Background - We have to use the terrain of the Terra plugin, and only then use our own plugin to replace the blocks with custom ones. Everything should be fine, BUT! Adding each block to the cache is very loaded on the server, and there can be 512 or more blocks in the chunk. After the start of the download, sooner or later IA crashes the server with this error in the console 
https://mcpaste.io/1595c0d127cd70dc
https://mcpaste.io/5c784b7533a3a4ba

I have already suggested making an option to disable the cache in issue #759. We don't have any music blocks on the server, and we don't care if they can't be used.

I don't know if it's a suggestion or a bug, but we need help with this damn shit.

[Addition], also very often after adding new blocks to the server, the old ones may simply break. I do not have any proofs with this error, but it is so

ItemsAdder 2.3.9
ItemsAdderApi 2.3.8

The part of the code where the blocks are placed: https://pastebin.com/EmgnQMMH

**Comment by Venterok** [comment]
Breaks everything on the line " custom block.place". We believe that this is all due to the addition of the block to the cache

**Comment by LoneDev6** [comment]
I sincerely have no idea of why you're editing the cache manually nor what you mean with "the old ones may simply break".
You must not edit cache files manually by any reason.
I may add Terra compatibility in the future, as you can see I work hard to add compatibility to as many plugins as I can https://itemsadder.plugin.ga/compatibility-with-other-plugins/compatible
For now I simply don't have the time, as you can see there are other 82 requests on this GitHub issues page.

Anyway I also don't understand what do I have to check in your code, what's wrong with the code? What is not working exactly?

**Comment by RuverQ** [comment]
_[I'm collaborating with Venterok]_

So, we are don't editing the cache manually. My plugin generates new blocks on early generated chunks. And when my plugin generates X amount of CustomBlocks `customblock.place(block.getLocation())` server just crashes. The server doesn't crash if my plugin generates default blocks. 

I've no idea why does this happen.

**Comment by RuverQ** [comment]
My plugin generates millions of blocks. Probably it's related to saving custom blocks to cache. idk

**Comment by RuverQ** [comment]
Maybe save blocks asynchronously? or in another thread? I think cache saving synchronous because there's a little lag  when saving every minute.

Is ItemsAdder checks ALL the blocks every minute?

**Comment by Venterok** [comment]
Tps & Timings with ItemsAdder saving. Every 1 minute Timings increase to 150 - 500
![image](https://user-images.githubusercontent.com/67825103/119973532-44905a80-bfbc-11eb-94b2-210f40ebd348.png)

**Comment by Venterok** [comment]
Tps & Timings without ItemsAdder saving
![image](https://user-images.githubusercontent.com/67825103/119973699-79041680-bfbc-11eb-8c06-95539972145a.png)

**Comment by Venterok** [comment]
The server does not have weak characteristics and it will not lag every minute. We really think that ItemsAdder has very big problems with cache retention

**Comment by SirCraftypants** [comment]
I don;t believe this is an Itemsadder issue, as you've stated you have created another plugin to get Itemsadder to do what it wasn't supposed to do. 

As LoneDev has stated he will look in to making Itemsadder compatible with Terra as soon as he has the time. The few support team he has including me do our best to lesson the workload for Lonedev so that he can concentrate on the Plugins but his Plugins are popular as you can see so with that, there's a lot of users requiring support. 

Lonedev will do his best to support you on this matter, all he wishes for is that you be patient.

**Comment by SirCraftypants** [comment]
This also may interest you. https://github.com/PluginBugs/Issues-ItemsAdder/issues/882

**Comment by Venterok** [comment]
> 
> 
> I don't believe this is an Itemsadder issue, as you've stated you have created another plugin to get Itemsadder to do what it wasn't supposed to do.
> 
> As LoneDev has stated he will look in to making Itemsadder compatible with Terra as soon as he has the time. The few support team he has including me do our best to lesson the workload for Lonedev so that he can concentrate on the Plugins but his Plugins are popular as you can see so with that, there's a lot of users requiring support.
> 
> Lonedev will do his best to support you on this matter, all he wishes for is that you be patient.

This is not a problem with our plugin, not with Terra support, but with terrible block caching, which is why everything is lagging. ItemsAdder tries to load all the custom blocks in the world every minute, which causes a lot of lags and in some cases crashes if there are a couple of million blocks in the cache

**Comment by Venterok** [comment]
We don't need Terra support, we didn't write about it in the issue. We want LoneDev to fix block caching. It prevents us from using the API and in general ItemsAdder is normal when you have a couple of million blocks in the world.

**Comment by SirCraftypants** [comment]
> 
> 
> > I don't believe this is an Itemsadder issue, as you've stated you have created another plugin to get Itemsadder to do what it wasn't supposed to do.
> > As LoneDev has stated he will look in to making Itemsadder compatible with Terra as soon as he has the time. The few support team he has including me do our best to lesson the workload for Lonedev so that he can concentrate on the Plugins but his Plugins are popular as you can see so with that, there's a lot of users requiring support.
> > Lonedev will do his best to support you on this matter, all he wishes for is that you be patient.
> 
> This is not a problem with our plugin, not with Terra support, but with terrible block caching, which is why everything is lagging. ItemsAdder tries to load all the custom blocks in the world every minute, which causes a lot of lags and in some cases crashes if there are a couple of million blocks in the cache

You're forcing Itemsadder with your plugin and Terra to do what Itemsadder isn't set to do, saying it's Itemsadders fault when Itemsadder clearly doesn't say it's compatible with Terra is disrespectful to say the least.

**Comment by SirCraftypants** [comment]
Another way of putting it is, you've purchased a V6 engine expecting it to do the job of a V12 engine. Lonedev has said when he gets the time he will look in to it but you need to fully explain exactly what the issues are in detail and provide any code so he can get to the bottom of the issue. Instead of laying all the blame on Itemsadder when you're clearly throttling it with your plugin and expecting it to do more than it should be doing.

**Comment by RuverQ** [comment]
Why is there API for this then? For not using it? I just want to place many many blocks, but I can't and that's all. I know the issue in ItemsAdder. And I know that this can be solved. We are shown the code if you not seen it already. 

To solve this problem we need:
Disabling caching option OR Advance the saving cache saving thing

**Comment by LoneDev6** [comment]
If you're calling `CustomBlock.getInstance` on each block spawn without caching the result yes, the server may lag because you're constantly asking itemsadder to search in its registry for the block id and get an instance of it.
In order to optimize you can try to cache the `ore.getMaterial()` result into an HashMap<String, CustomBlock>, then if it's already there you just get the Customblock instance call `place`.
You can use the same CustomBlock instance to place blocks around (if you need to place the same block id, if you need another custom block id you have to get another instance).

ItemsAdder api is async, yes. It's not very safe but that's the only way to make the plugin efficient.
Also you may try to ask RealisticWorldGenerator dev to know how they managed to make it working fine since they said it's compatible with ItemsAdder.

(note that if you try to spawn milions of blocks using spigot api you won't get great performance too, I bet).

Let me know.
Anyway try to keep the messages number as low as possible, if you can please edit your last message if you need to add more info, avoid sending multiple messages. Thanks!

**Comment by RuverQ** [comment]
So.. yeah thanks! Delay in generating is working without crashing.

**But** after finishing generating 3750x3750 radius of blocks ItemsAdder overloading the CPU for some reason:
timings: https://timings.pl3x.net/?id=dfd790fc575a49f3b01916a77f8ec121

**Comment by LoneDev6** [comment]
Since I have no screenshot of some parts of the generated world I can only assume that it's because something is triggering block physics a log on custom blocks.
Anyway reading the timings report seems that fire is triggering the spigot physics events a lot.
I suggest you to disable custom fire in `config.yml` if you want, let me know how it goes.
`  disable-CUSTOM_FIRE-behaviour: true`


Also, due to the fact that your world is very huge and you want to populate it using custom blocks, I also suggest you to pre-generate the world to avoid slowdown (which also every other custom world generation plugin developer would say to you).

**Comment by RuverQ** [comment]
> I suggest you to disable custom fire in `config.yml` if you want, let me know how it goes.
> `  disable-CUSTOM_FIRE-behaviour: true`

It completely fixed a problem! That's all i want Thanks! 

Thank you very much and sorry for our incompetence.

**Comment by LoneDev6** [comment]
> 
> 
> > I suggest you to disable custom fire in `config.yml` if you want, let me know how it goes.
> > `  disable-CUSTOM_FIRE-behaviour: true`
> 
> It completely fixed a problem! That's all i want Thanks!
> 
> Thank you very much and sorry for our incompetence.

No problem, I'm happy we managed to make all the system working, can't wait to see what you created 👍🏻 

I hope you will consider leaving a 5 stars review, this will help me to be motivated to add new features to the plugin :D
